// ply-reader.cc - C++ native addon for PLY parsing + compressed-ply writing
// Replaces server.js readPlyFast + splat-transform writeCompressedPly JS loops
//
// Key optimizations:
//   1. mmap/MapViewOfFile for zero-copy file reads
//   2. Direct column scatter (no JS overhead)
//   3. C++ morton sort + chunk packing (no V8 GC pressure)
//   4. Single-pass output file write

#include <napi.h>

#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#endif

#include <string>
#include <vector>
#include <cmath>
#include <algorithm>
#include <cstring>
#include <sstream>
#include <cstdint>
#include <cstdio>

#ifndef _WIN32
#include <sys/mman.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#endif

// ========== Constants (must match splat-transform) ==========
static constexpr size_t CHUNK_SIZE = 256;
static constexpr float SH_C0 = 0.28209479177387814f;
static const char* GENERATED_BY = "Generated by splat-transform 2.3.1";

static const char* chunkProps[] = {
    "min_x", "min_y", "min_z",
    "max_x", "max_y", "max_z",
    "min_scale_x", "min_scale_y", "min_scale_z",
    "max_scale_x", "max_scale_y", "max_scale_z",
    "min_r", "min_g", "min_b",
    "max_r", "max_g", "max_b"
};
static constexpr size_t NUM_CHUNK_PROPS = 18;

static const char* vertexProps[] = {
    "packed_position",
    "packed_rotation",
    "packed_scale",
    "packed_color"
};
static constexpr size_t NUM_VERTEX_PROPS = 4;

// ========== Platform-specific memory mapping ==========
#ifdef _WIN32

// Windows: convert UTF-8 path to wide-char for Unicode support
static std::wstring utf8ToWide(const std::string& utf8) {
    if (utf8.empty()) return L"";
    int len = MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), -1, nullptr, 0);
    if (len <= 0) return L"";
    std::wstring wide(len - 1, L'\0');
    MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), -1, &wide[0], len);
    return wide;
}

#endif

class MappedFile {
    void* m_data;
    size_t m_size;
#ifdef _WIN32
    HANDLE m_file;
    HANDLE m_mapping;
#endif
public:
    MappedFile(const char* path)
        : m_data(nullptr), m_size(0)
#ifdef _WIN32
        , m_file(INVALID_HANDLE_VALUE), m_mapping(nullptr)
#endif
    {
#ifdef _WIN32
        std::wstring wPath = utf8ToWide(path);
        m_file = CreateFileW(wPath.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr,
                             OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr);
        if (m_file == INVALID_HANDLE_VALUE) return;

        LARGE_INTEGER fileSize;
        if (!GetFileSizeEx(m_file, &fileSize)) {
            CloseHandle(m_file);
            m_file = INVALID_HANDLE_VALUE;
            return;
        }
        m_size = static_cast<size_t>(fileSize.QuadPart);

        m_mapping = CreateFileMappingW(m_file, nullptr, PAGE_READONLY, 0, 0, nullptr);
        if (!m_mapping) {
            CloseHandle(m_file);
            m_file = INVALID_HANDLE_VALUE;
            return;
        }

        m_data = MapViewOfFile(m_mapping, FILE_MAP_READ, 0, 0, 0);
#else
        int fd = open(path, O_RDONLY);
        if (fd < 0) return;

        struct stat st;
        if (fstat(fd, &st) < 0) {
            close(fd);
            return;
        }
        m_size = static_cast<size_t>(st.st_size);

        m_data = mmap(nullptr, m_size, PROT_READ, MAP_PRIVATE, fd, 0);
        if (m_data == MAP_FAILED) {
            m_data = nullptr;
            close(fd);
            return;
        }
        close(fd);
#endif
    }

    ~MappedFile() {
#ifdef _WIN32
        if (m_data) UnmapViewOfFile(m_data);
        if (m_mapping) CloseHandle(m_mapping);
        if (m_file != INVALID_HANDLE_VALUE) CloseHandle(m_file);
#else
        if (m_data) munmap(m_data, m_size);
#endif
    }

    void* data() const { return m_data; }
    size_t size() const { return m_size; }
    bool valid() const { return m_data != nullptr; }
};

// ========== PLY header parsing ==========
struct PlyProperty {
    std::string type;
    std::string name;
};

struct PlyElement {
    std::string name;
    int count;
    std::vector<PlyProperty> properties;
};

struct PlyHeader {
    std::vector<PlyElement> elements;
    size_t binaryStart;
    bool isCompressed;
};

static PlyHeader parsePlyHeader(const char* data, size_t size) {
    PlyHeader header;
    header.binaryStart = 0;
    header.isCompressed = false;

    // Find "\nend_header\n"
    const char* endMarker = "\nend_header\n";
    size_t endLen = 13;
    const char* pos = nullptr;

    // Search within first 128KB (headers are small)
    size_t searchLen = std::min(size, static_cast<size_t>(128 * 1024));
    for (size_t i = 0; i + endLen <= searchLen; ++i) {
        if (std::memcmp(data + i, endMarker, endLen) == 0) {
            pos = data + i;
            header.binaryStart = i + endLen;
            break;
        }
    }

    if (!pos) {
        // Try "end_header\n" at start (no leading newline)
        const char* endMarker2 = "end_header\n";
        size_t endLen2 = 11;
        for (size_t i = 0; i + endLen2 <= searchLen; ++i) {
            if (std::memcmp(data + i, endMarker2, endLen2) == 0) {
                header.binaryStart = i + endLen2;
                pos = data + i;
                break;
            }
        }
        if (!pos) return header;
    }

    // Parse header lines
    std::string headerStr(data, pos);
    std::istringstream iss(headerStr);
    std::string line;
    PlyElement* current = nullptr;

    while (std::getline(iss, line)) {
        // Strip \r
        if (!line.empty() && line.back() == '\r') line.pop_back();

        std::istringstream ls(line);
        std::string word;
        ls >> word;

        if (word == "ply" || word == "format" || word == "end_header" || word.empty() || word == "comment") {
            continue;
        } else if (word == "element") {
            std::string name;
            int count;
            ls >> name >> count;
            header.elements.push_back({name, count, {}});
            current = &header.elements.back();
        } else if (word == "property" && current) {
            std::string type, name;
            ls >> type >> name;
            current->properties.push_back({type, name});
        }
    }

    // Check if compressed PLY (chunk + vertex elements)
    if (header.elements.size() == 2 &&
        header.elements[0].name == "chunk" &&
        header.elements[1].name == "vertex") {
        header.isCompressed = true;
    }

    return header;
}

// ========== Morton encoding ==========
static inline uint32_t part1By2(uint32_t x) {
    x &= 0x000003ff;
    x = (x ^ (x << 16)) & 0xff0000ff;
    x = (x ^ (x << 8)) & 0x0300f00f;
    x = (x ^ (x << 4)) & 0x030c30c3;
    x = (x ^ (x << 2)) & 0x09249249;
    return x;
}

static inline uint32_t encodeMorton3(uint32_t x, uint32_t y, uint32_t z) {
    return (part1By2(z) << 2) + (part1By2(y) << 1) + part1By2(x);
}

// Recursive morton sort — matches splat-transform sortMortonOrder
static void sortMortonRecursive(
    const float* cx, const float* cy, const float* cz,
    uint32_t* indices, size_t n
) {
    if (n == 0) return;

    // Calculate extents
    float mx = INFINITY, my = INFINITY, mz = INFINITY;
    float Mx = -INFINITY, My = -INFINITY, Mz = -INFINITY;

    for (size_t i = 0; i < n; ++i) {
        uint32_t ri = indices[i];
        float x = cx[ri], y = cy[ri], z = cz[ri];
        if (x < mx) mx = x;
        if (x > Mx) Mx = x;
        if (y < my) my = y;
        if (y > My) My = y;
        if (z < mz) mz = z;
        if (z > Mz) Mz = z;
    }

    float xlen = Mx - mx;
    float ylen = My - my;
    float zlen = Mz - mz;

    if (!std::isfinite(xlen) || !std::isfinite(ylen) || !std::isfinite(zlen)) return;
    if (xlen == 0 && ylen == 0 && zlen == 0) return;

    float xmul = (xlen == 0) ? 0.0f : 1024.0f / xlen;
    float ymul = (ylen == 0) ? 0.0f : 1024.0f / ylen;
    float zmul = (zlen == 0) ? 0.0f : 1024.0f / zlen;

    // Compute morton codes
    std::vector<uint32_t> morton(n);
    for (size_t i = 0; i < n; ++i) {
        uint32_t ri = indices[i];
        uint32_t ix = std::min(1023u, static_cast<uint32_t>((cx[ri] - mx) * xmul));
        uint32_t iy = std::min(1023u, static_cast<uint32_t>((cy[ri] - my) * ymul));
        uint32_t iz = std::min(1023u, static_cast<uint32_t>((cz[ri] - mz) * zmul));
        morton[i] = encodeMorton3(ix, iy, iz);
    }

    // Sort indices by morton code (stable sort to match JS Array.sort behavior)
    std::vector<uint32_t> order(n);
    for (size_t i = 0; i < n; ++i) order[i] = static_cast<uint32_t>(i);

    std::stable_sort(order.begin(), order.end(), [&](uint32_t a, uint32_t b) {
        return morton[a] < morton[b];
    });

    // Apply sorted order
    std::vector<uint32_t> tmp(indices, indices + n);
    for (size_t i = 0; i < n; ++i) {
        indices[i] = tmp[order[i]];
    }

    // Recursively sort buckets > 256 with same morton code
    size_t start = 0;
    size_t end = 1;
    while (start < n) {
        while (end < n && morton[order[end]] == morton[order[start]]) {
            ++end;
        }
        if (end - start > 256) {
            sortMortonRecursive(cx, cy, cz, indices + start, end - start);
        }
        start = end;
    }
}

// ========== Packing helpers ==========
static inline int packUnorm(float value, int bits) {
    int t = (1 << bits) - 1;
    int v = static_cast<int>(std::floor(value * t + 0.5f));
    return std::max(0, std::min(t, v));
}

static inline uint32_t pack111011(float x, float y, float z) {
    return (static_cast<uint32_t>(packUnorm(x, 11)) << 21) |
           (static_cast<uint32_t>(packUnorm(y, 10)) << 11) |
           static_cast<uint32_t>(packUnorm(z, 11));
}

static inline uint32_t pack8888(float x, float y, float z, float w) {
    return (static_cast<uint32_t>(packUnorm(x, 8)) << 24) |
           (static_cast<uint32_t>(packUnorm(y, 8)) << 16) |
           (static_cast<uint32_t>(packUnorm(z, 8)) << 8) |
           static_cast<uint32_t>(packUnorm(w, 8));
}

static inline float sigmoidVal(float v) {
    return 1.0f / (1.0f + std::exp(-v));
}

static inline float normalizeVal(float x, float min, float max) {
    if (x <= min) return 0.0f;
    if (x >= max) return 1.0f;
    return (max - min < 0.00001f) ? 0.0f : (x - min) / (max - min);
}

static inline float clampf(float v, float lo, float hi) {
    return std::max(lo, std::min(hi, v));
}

// Pack quaternion into 2-10-10-10 format (matches splat-transform packRot)
static uint32_t packRot(float x, float y, float z, float w) {
    // Normalize quaternion
    float mag = std::sqrt(x * x + y * y + z * z + w * w);
    if (mag > 0.0f) {
        float inv = 1.0f / mag;
        x *= inv; y *= inv; z *= inv; w *= inv;
    }

    float a[4] = {x, y, z, w};

    // Find largest component
    int largest = 0;
    for (int i = 1; i < 4; ++i) {
        if (std::abs(a[i]) > std::abs(a[largest])) largest = i;
    }

    // Negate all if largest < 0
    if (a[largest] < 0.0f) {
        for (int i = 0; i < 4; ++i) a[i] = -a[i];
    }

    float norm = std::sqrt(2.0f) * 0.5f;
    uint32_t result = static_cast<uint32_t>(largest);
    for (int i = 0; i < 4; ++i) {
        if (i != largest) {
            result = (result << 10) | static_cast<uint32_t>(packUnorm(a[i] * norm + 0.5f, 10));
        }
    }
    return result;
}

// ========== N-API: readPlyFast ==========
// Returns { columns: [{name, data: Float32Array}], numRows: number }
static Napi::Value ReadPlyFast(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();

    if (info.Length() < 1 || !info[0].IsString()) {
        Napi::TypeError::New(env, "Expected file path string").ThrowAsJavaScriptException();
        return env.Null();
    }

    std::string filePath = info[0].As<Napi::String>().Utf8Value();

    MappedFile mapped(filePath.c_str());
    if (!mapped.valid()) {
        Napi::Error::New(env, "Failed to open/mmap file: " + filePath).ThrowAsJavaScriptException();
        return env.Null();
    }

    const char* fileData = static_cast<const char*>(mapped.data());
    size_t fileSize = mapped.size();

    // Parse header
    PlyHeader header = parsePlyHeader(fileData, fileSize);
    if (header.binaryStart == 0) {
        Napi::Error::New(env, "end_header not found in PLY").ThrowAsJavaScriptException();
        return env.Null();
    }

    if (header.isCompressed) {
        Napi::Error::New(env, "Compressed PLY not supported in fast path").ThrowAsJavaScriptException();
        return env.Null();
    }

    // Find vertex element
    const PlyElement* vertexEl = nullptr;
    for (const auto& el : header.elements) {
        if (el.name == "vertex") {
            vertexEl = &el;
            break;
        }
    }
    if (!vertexEl) {
        Napi::Error::New(env, "No vertex element in PLY").ThrowAsJavaScriptException();
        return env.Null();
    }

    int numRows = vertexEl->count;
    int numProps = static_cast<int>(vertexEl->properties.size());

    // Verify all-float properties
    for (const auto& prop : vertexEl->properties) {
        if (prop.type != "float") {
            Napi::Error::New(env, "Non-float PLY properties not supported in fast path").ThrowAsJavaScriptException();
            return env.Null();
        }
    }

    // Allocate Float32Array columns and scatter data
    const char* binaryData = fileData + header.binaryStart;
    size_t rowSize = static_cast<size_t>(numProps) * 4;

    Napi::Array columns = Napi::Array::New(env, numProps);
    std::vector<float*> colPtrs(numProps);

    for (int p = 0; p < numProps; ++p) {
        Napi::Float32Array arr = Napi::Float32Array::New(env, numRows);
        colPtrs[p] = arr.Data();
        Napi::Object colObj = Napi::Object::New(env);
        colObj.Set("name", Napi::String::New(env, vertexEl->properties[p].name));
        colObj.Set("data", arr);
        columns.Set(static_cast<uint32_t>(p), colObj);
    }

    // Scatter: row-major → column-major
    for (int r = 0; r < numRows; ++r) {
        const float* row = reinterpret_cast<const float*>(binaryData + r * rowSize);
        for (int p = 0; p < numProps; ++p) {
            colPtrs[p][r] = row[p];
        }
    }

    Napi::Object result = Napi::Object::New(env);
    result.Set("columns", columns);
    result.Set("numRows", Napi::Number::New(env, numRows));
    return result;
}

// ========== N-API: writeCompressedPly ==========
// params: {
//   columns: { [name: string]: Float32Array },
//   numRows: number,
//   outputPath: string,
//   shBands: number  (0, 1, 2, or 3)
// }
static Napi::Value WriteCompressedPly(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();

    if (info.Length() < 1 || !info[0].IsObject()) {
        Napi::TypeError::New(env, "Expected params object").ThrowAsJavaScriptException();
        return env.Null();
    }

    Napi::Object params = info[0].As<Napi::Object>();
    Napi::Object columns = params.Get("columns").As<Napi::Object>();
    int numRows = params.Get("numRows").As<Napi::Number>().Int32Value();
    std::string outputPath = params.Get("outputPath").As<Napi::String>().Utf8Value();
    int shBands = params.Get("shBands").As<Napi::Number>().Int32Value();

    int outputSHCoeffs = (shBands == 0) ? 0 : (shBands == 1) ? 3 : (shBands == 2) ? 8 : 15;

    // Get column data pointers
    auto getCol = [&](const char* name) -> float* {
        Napi::Value val = columns.Get(name);
        if (val.IsUndefined() || val.IsNull()) return nullptr;
        return val.As<Napi::Float32Array>().Data();
    };

    float* cx = getCol("x");
    float* cy = getCol("y");
    float* cz = getCol("z");
    float* cs0 = getCol("scale_0");
    float* cs1 = getCol("scale_1");
    float* cs2 = getCol("scale_2");
    float* cr0 = getCol("rot_0");
    float* cr1 = getCol("rot_1");
    float* cr2 = getCol("rot_2");
    float* cr3 = getCol("rot_3");
    float* cdc0 = getCol("f_dc_0");
    float* cdc1 = getCol("f_dc_1");
    float* cdc2 = getCol("f_dc_2");
    float* cop = getCol("opacity");

    if (!cx || !cy || !cz || !cs0 || !cs1 || !cs2 ||
        !cr0 || !cr1 || !cr2 || !cr3 ||
        !cdc0 || !cdc1 || !cdc2 || !cop) {
        Napi::Error::New(env, "Missing required column(s)").ThrowAsJavaScriptException();
        return env.Null();
    }

    // Get SH rest columns
    std::vector<float*> shRestCols;
    if (outputSHCoeffs > 0) {
        shRestCols.resize(outputSHCoeffs * 3);
        for (int k = 0; k < outputSHCoeffs * 3; ++k) {
            std::string name = "f_rest_" + std::to_string(k);
            shRestCols[k] = getCol(name.c_str());
            if (!shRestCols[k]) {
                Napi::Error::New(env, "Missing SH column: " + name).ThrowAsJavaScriptException();
                return env.Null();
            }
        }
    }

    int numSplats = numRows;
    int numChunks = (numSplats + CHUNK_SIZE - 1) / CHUNK_SIZE;

    // --- Step 1: Morton sort ---
    std::vector<uint32_t> sortIndices(numSplats);
    for (int i = 0; i < numSplats; ++i) sortIndices[i] = static_cast<uint32_t>(i);
    sortMortonRecursive(cx, cy, cz, sortIndices.data(), static_cast<size_t>(numSplats));

    // --- Step 2: Allocate output buffers ---
    std::vector<float> chunkData(numChunks * NUM_CHUNK_PROPS);
    std::vector<uint32_t> splatIData(numSplats * NUM_VERTEX_PROPS);
    std::vector<uint8_t> shData;
    if (outputSHCoeffs > 0) {
        shData.resize(static_cast<size_t>(numSplats) * outputSHCoeffs * 3);
    }

    // Temporary chunk buffers (stack-allocated, 256 entries each)
    float dc0[CHUNK_SIZE], dc1[CHUNK_SIZE], dc2[CHUNK_SIZE];

    // --- Step 3: Process chunks ---
    for (int ci = 0; ci < numChunks; ++ci) {
        int num = std::min(numSplats, (ci + 1) * static_cast<int>(CHUNK_SIZE)) - ci * static_cast<int>(CHUNK_SIZE);

        // Convert f_dc to colors (in-place conversion to temporary buffer)
        for (int j = 0; j < num; ++j) {
            uint32_t idx = sortIndices[ci * CHUNK_SIZE + j];
            dc0[j] = cdc0[idx] * SH_C0 + 0.5f;
            dc1[j] = cdc1[idx] * SH_C0 + 0.5f;
            dc2[j] = cdc2[idx] * SH_C0 + 0.5f;
        }
        // Fill rest of chunk with last gaussian
        for (int j = num; j < static_cast<int>(CHUNK_SIZE); ++j) {
            dc0[j] = dc0[num - 1];
            dc1[j] = dc1[num - 1];
            dc2[j] = dc2[num - 1];
        }

        // Quantize SH data for this chunk's splats
        if (outputSHCoeffs > 0) {
            for (int j = 0; j < num; ++j) {
                uint32_t idx = sortIndices[ci * CHUNK_SIZE + j];
                size_t off = static_cast<size_t>(ci * CHUNK_SIZE + j) * outputSHCoeffs * 3;
                for (int k = 0; k < outputSHCoeffs * 3; ++k) {
                    float nvalue = shRestCols[k][idx] / 8.0f + 0.5f;
                    int val = static_cast<int>(nvalue * 256.0f);
                    shData[off++] = static_cast<uint8_t>(std::max(0, std::min(255, val)));
                }
            }
        }

        // --- Calculate min/max for each attribute (only over valid num entries) ---

        // Position min/max (gather from source arrays using sorted indices)
        const uint32_t* chunkIdx = &sortIndices[ci * CHUNK_SIZE];
        float pmx = cx[chunkIdx[0]], pMx = cx[chunkIdx[0]];
        float pmy = cy[chunkIdx[0]], pMy = cy[chunkIdx[0]];
        float pmz = cz[chunkIdx[0]], pMz = cz[chunkIdx[0]];
        for (int j = 1; j < num; ++j) {
            uint32_t idx = chunkIdx[j];
            float vx = cx[idx], vy = cy[idx], vz = cz[idx];
            if (vx < pmx) pmx = vx; if (vx > pMx) pMx = vx;
            if (vy < pmy) pmy = vy; if (vy > pMy) pMy = vy;
            if (vz < pmz) pmz = vz; if (vz > pMz) pMz = vz;
        }

        // Scale min/max (gather + clamp to [-20, 20])
        float smx = cs0[chunkIdx[0]], sMx = cs0[chunkIdx[0]];
        float smy = cs1[chunkIdx[0]], sMy = cs1[chunkIdx[0]];
        float smz = cs2[chunkIdx[0]], sMz = cs2[chunkIdx[0]];
        for (int j = 1; j < num; ++j) {
            uint32_t idx = chunkIdx[j];
            float vs0 = cs0[idx], vs1 = cs1[idx], vs2 = cs2[idx];
            if (vs0 < smx) smx = vs0; if (vs0 > sMx) sMx = vs0;
            if (vs1 < smy) smy = vs1; if (vs1 > sMy) sMy = vs1;
            if (vs2 < smz) smz = vs2; if (vs2 > sMz) sMz = vs2;
        }
        smx = clampf(smx, -20.0f, 20.0f); sMx = clampf(sMx, -20.0f, 20.0f);
        smy = clampf(smy, -20.0f, 20.0f); sMy = clampf(sMy, -20.0f, 20.0f);
        smz = clampf(smz, -20.0f, 20.0f); sMz = clampf(sMz, -20.0f, 20.0f);

        // Color min/max (from converted f_dc temp buffer — full 256 is safe due to fill)
        float crmn = dc0[0], crmx = dc0[0];
        float cgmn = dc1[0], cgmx = dc1[0];
        float cbmn = dc2[0], cbmx = dc2[0];
        for (int j = 1; j < static_cast<int>(CHUNK_SIZE); ++j) {
            float vr = dc0[j], vg = dc1[j], vb = dc2[j];
            if (vr < crmn) crmn = vr; if (vr > crmx) crmx = vr;
            if (vg < cgmn) cgmn = vg; if (vg > cgmx) cgmx = vg;
            if (vb < cbmn) cbmn = vb; if (vb > cbmx) cbmx = vb;
        }

        // Pack splats (only num entries are written)
        for (int j = 0; j < num; ++j) {
            uint32_t idx = chunkIdx[j];

            float nx = normalizeVal(cx[idx], pmx, pMx);
            float ny = normalizeVal(cy[idx], pmy, pMy);
            float nz = normalizeVal(cz[idx], pmz, pMz);
            uint32_t pos = pack111011(nx, ny, nz);

            uint32_t rot = packRot(cr0[idx], cr1[idx], cr2[idx], cr3[idx]);

            float ns0 = normalizeVal(cs0[idx], smx, sMx);
            float ns1 = normalizeVal(cs1[idx], smy, sMy);
            float ns2 = normalizeVal(cs2[idx], smz, sMz);
            uint32_t scl = pack111011(ns0, ns1, ns2);

            float ndc0 = normalizeVal(dc0[j], crmn, crmx);
            float ndc1 = normalizeVal(dc1[j], cgmn, cgmx);
            float ndc2 = normalizeVal(dc2[j], cbmn, cbmx);
            float nopa = sigmoidVal(cop[idx]);
            uint32_t col = pack8888(ndc0, ndc1, ndc2, nopa);

            size_t off = static_cast<size_t>(ci * CHUNK_SIZE + j) * 4;
            splatIData[off] = pos;
            splatIData[off + 1] = rot;
            splatIData[off + 2] = scl;
            splatIData[off + 3] = col;
        }

        // Store chunk metadata (18 floats)
        float* cd = &chunkData[ci * NUM_CHUNK_PROPS];
        cd[0] = pmx;  cd[1] = pmy;  cd[2] = pmz;
        cd[3] = pMx;  cd[4] = pMy;  cd[5] = pMz;
        cd[6] = smx;  cd[7] = smy;  cd[8] = smz;
        cd[9] = sMx;  cd[10] = sMy; cd[11] = sMz;
        cd[12] = crmn; cd[13] = cgmn; cd[14] = cbmn;
        cd[15] = crmx; cd[16] = cgmx; cd[17] = cbmx;
    }

    // --- Step 4: Build header ---
    std::ostringstream hdr;
    hdr << "ply\n";
    hdr << "format binary_little_endian 1.0\n";
    hdr << "comment " << GENERATED_BY << "\n";
    hdr << "element chunk " << numChunks << "\n";
    for (size_t i = 0; i < NUM_CHUNK_PROPS; ++i) {
        hdr << "property float " << chunkProps[i] << "\n";
    }
    hdr << "element vertex " << numSplats << "\n";
    for (size_t i = 0; i < NUM_VERTEX_PROPS; ++i) {
        hdr << "property uint " << vertexProps[i] << "\n";
    }
    if (shBands > 0) {
        hdr << "element sh " << numSplats << "\n";
        for (int i = 0; i < outputSHCoeffs * 3; ++i) {
            hdr << "property uchar f_rest_" << i << "\n";
        }
    }
    hdr << "end_header\n";

    std::string headerStr = hdr.str();

    // --- Step 5: Write output file ---
#ifdef _WIN32
    std::wstring wOutputPath = utf8ToWide(outputPath);
    FILE* fp = _wfopen(wOutputPath.c_str(), L"wb");
#else
    FILE* fp = std::fopen(outputPath.c_str(), "wb");
#endif
    if (!fp) {
        Napi::Error::New(env, "Failed to open output file: " + outputPath).ThrowAsJavaScriptException();
        return env.Null();
    }

    std::fwrite(headerStr.data(), 1, headerStr.size(), fp);
    std::fwrite(chunkData.data(), sizeof(float), chunkData.size(), fp);
    std::fwrite(splatIData.data(), sizeof(uint32_t), splatIData.size(), fp);
    if (outputSHCoeffs > 0) {
        std::fwrite(shData.data(), 1, shData.size(), fp);
    }

    size_t bytesWritten = headerStr.size() +
                          chunkData.size() * sizeof(float) +
                          splatIData.size() * sizeof(uint32_t) +
                          (outputSHCoeffs > 0 ? shData.size() : 0);
    std::fclose(fp);

    Napi::Object result = Napi::Object::New(env);
    result.Set("bytesWritten", Napi::Number::New(env, static_cast<double>(bytesWritten)));
    result.Set("numChunks", Napi::Number::New(env, numChunks));
    result.Set("numSplats", Napi::Number::New(env, numSplats));
    return result;
}

// ========== N-API: mergePlyFiles ==========
// Takes an array of PLY file paths, merges them by concatenating column data.
// Property alignment: uses the union of all column names, fills missing with zeros.
static Napi::Value MergePlyFiles(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();

    if (info.Length() < 1 || !info[0].IsArray()) {
        Napi::TypeError::New(env, "Expected array of file paths").ThrowAsJavaScriptException();
        return env.Null();
    }

    Napi::Array paths = info[0].As<Napi::Array>();
    int numFiles = static_cast<int>(paths.Length());
    if (numFiles < 2) {
        Napi::Error::New(env, "Need at least 2 files to merge").ThrowAsJavaScriptException();
        return env.Null();
    }

    // --- Pass 1: scan headers, collect all property names, count total rows ---
    struct FileInfo {
        std::string path;
        std::vector<std::string> propNames;
        int numRows;
        size_t binaryStart;
    };
    std::vector<FileInfo> fileInfos;
    std::vector<std::string> allPropNames;
    uint64_t totalRows = 0;

    for (int fi = 0; fi < numFiles; ++fi) {
        std::string filePath = paths.Get(static_cast<uint32_t>(fi)).As<Napi::String>().Utf8Value();

        MappedFile mapped(filePath.c_str());
        if (!mapped.valid()) {
            Napi::Error::New(env, "Failed to open file: " + filePath).ThrowAsJavaScriptException();
            return env.Null();
        }

        const char* fileData = static_cast<const char*>(mapped.data());
        PlyHeader header = parsePlyHeader(fileData, mapped.size());

        const PlyElement* vertexEl = nullptr;
        for (const auto& el : header.elements) {
            if (el.name == "vertex") { vertexEl = &el; break; }
        }
        if (!vertexEl) {
            Napi::Error::New(env, "No vertex element in: " + filePath).ThrowAsJavaScriptException();
            return env.Null();
        }

        FileInfo fi2;
        fi2.path = filePath;
        fi2.numRows = vertexEl->count;
        fi2.binaryStart = header.binaryStart;
        for (const auto& prop : vertexEl->properties) {
            fi2.propNames.push_back(prop.name);
            // Add to union set if not already present
            bool found = false;
            for (const auto& existing : allPropNames) {
                if (existing == prop.name) { found = true; break; }
            }
            if (!found) allPropNames.push_back(prop.name);
        }
        fileInfos.push_back(std::move(fi2));
        totalRows += static_cast<uint64_t>(vertexEl->count);
    }

    if (totalRows > static_cast<uint64_t>(std::numeric_limits<int>::max())) {
        Napi::Error::New(env, "Merged row count exceeds int32 range").ThrowAsJavaScriptException();
        return env.Null();
    }
    int mergedRows = static_cast<int>(totalRows);
    int numProps = static_cast<int>(allPropNames.size());

    // --- Pass 2: allocate output columns ---
    Napi::Array columns = Napi::Array::New(env, numProps);
    std::vector<float*> colPtrs(numProps);
    std::vector<size_t> colOffsets(numProps, 0);

    for (int p = 0; p < numProps; ++p) {
        Napi::Float32Array arr = Napi::Float32Array::New(env, mergedRows);
        colPtrs[p] = arr.Data();
        Napi::Object colObj = Napi::Object::New(env);
        colObj.Set("name", Napi::String::New(env, allPropNames[p]));
        colObj.Set("data", arr);
        columns.Set(static_cast<uint32_t>(p), colObj);
    }

    // --- Pass 3: copy data from each file ---
    size_t rowOffset = 0;

    for (int fi = 0; fi < numFiles; ++fi) {
        const FileInfo& finfo = fileInfos[fi];

        MappedFile mapped(finfo.path.c_str());
        const char* binaryData = static_cast<const char*>(mapped.data()) + finfo.binaryStart;
        int fileNumProps = static_cast<int>(finfo.propNames.size());
        size_t fileRowSize = static_cast<size_t>(fileNumProps) * 4;

        // Build mapping: global prop index → local prop index (-1 if not present)
        std::vector<int> propMap(numProps, -1);
        for (int gp = 0; gp < numProps; ++gp) {
            for (int lp = 0; lp < fileNumProps; ++lp) {
                if (finfo.propNames[lp] == allPropNames[gp]) {
                    propMap[gp] = lp;
                    break;
                }
            }
        }

        for (int r = 0; r < finfo.numRows; ++r) {
            const float* row = reinterpret_cast<const float*>(binaryData + r * fileRowSize);
            size_t dstRow = rowOffset + r;
            for (int gp = 0; gp < numProps; ++gp) {
                int lp = propMap[gp];
                colPtrs[gp][dstRow] = (lp >= 0) ? row[lp] : 0.0f;
            }
        }

        rowOffset += static_cast<size_t>(finfo.numRows);
    }

    Napi::Object result = Napi::Object::New(env);
    result.Set("columns", columns);
    result.Set("numRows", Napi::Number::New(env, mergedRows));
    result.Set("numProps", Napi::Number::New(env, numProps));
    return result;
}

// ========== Module init ==========
static Napi::Object Init(Napi::Env env, Napi::Object exports) {
    exports.Set(Napi::String::New(env, "readPlyFast"), Napi::Function::New(env, ReadPlyFast));
    exports.Set(Napi::String::New(env, "writeCompressedPly"), Napi::Function::New(env, WriteCompressedPly));
    exports.Set(Napi::String::New(env, "mergePlyFiles"), Napi::Function::New(env, MergePlyFiles));
    return exports;
}

NODE_API_MODULE(ply_reader, Init)
