import {
    Column,
    DataTable,
    logger as splatTransformLogger,
    MemoryFileSystem,
    Transform,
    WebPCodec,
    WorkerQueue,
    writeHtml,
    writeSog as writeSogInternal,
    ZipFileSystem,
    type FileSystem,
    type LogEvent,
    type Renderer,
    type Writer
} from '@playcanvas/splat-transform';
import {
    GSplatData,
    Mat3,
    Mat4,
    PIXELFORMAT_BGRA8,
    Quat,
    Texture,
    Vec3,
    WebgpuGraphicsDevice
} from 'playcanvas';

import { version } from '../package.json';
import { ColorGrade, dcDecode, dcEncode, sigmoid } from './color-grade';
import { Events } from './events';
import { BrowserFileSystem, ProgressWriter } from './io';
import { SHRotation } from './sh-utils';
import { Splat } from './splat';
import { State } from './splat-state';

type SerializeSettings = {
    maxSHBands?: number;            // specifies the maximum number of bands to be exported
    selected?: boolean;             // only export selected gaussians. used for copy/paste
    minOpacity?: number;            // filter out gaussians with alpha less than or equal to minAlpha
    removeInvalid?: boolean;        // filter out gaussians with invalid data (NaN/Infinity)

    // the following options are used when serializing the PLY for document save
    // and are only supported by serializePly
    keepStateData?: boolean;        // keep the state data array
    preserveDeleted?: boolean;      // keep deleted gaussians in vertex data (for index consistency)
    keepWorldTransform?: boolean;   // don't apply the world transform when resolving splat transforms
    keepColorTint?: boolean;        // refrain from applying color tints
    skipPlyRotation?: boolean;      // skip the 180° Z rotation for PLY coordinate system (used for in-memory merge)
};

type AnimTrack = {
    name: string,
    duration: number,
    frameRate: number,
    loopMode: 'none' | 'repeat' | 'pingpong',
    interpolation: 'step' | 'spline',
    smoothness: number,
    keyframes: {
        times: number[],
        values: {
            position: number[],
            target: number[],
            fov: number[],
        }
    }
};

type CameraPose = {
    position: [number, number, number],
    target: [number, number, number],
    fov: number
};

type Camera = {
    initial: CameraPose,
};

type Annotation = {
    position: [number, number, number],
    title: string,
    text: string,
    extras: any,
    camera: Camera
};

type PostEffectSettings = {
    sharpness: {
        enabled: boolean,
        amount: number,
    },
    bloom: {
        enabled: boolean,
        intensity: number,
        blurLevel: number,
    },
    grading: {
        enabled: boolean,
        brightness: number,
        contrast: number,
        saturation: number,
        tint: [number, number, number],
    },
    vignette: {
        enabled: boolean,
        intensity: number,
        inner: number,
        outer: number,
        curvature: number,
    },
    fringing: {
        enabled: boolean,
        intensity: number
    }
};

const defaultPostEffectSettings: PostEffectSettings = {
    sharpness: { enabled: false, amount: 0 },
    bloom: { enabled: false, intensity: 1, blurLevel: 2 },
    grading: { enabled: false, brightness: 1, contrast: 1, saturation: 1, tint: [1, 1, 1] },
    vignette: { enabled: false, intensity: 0.5, inner: 0.3, outer: 0.75, curvature: 1 },
    fringing: { enabled: false, intensity: 0.5 }
};

type ExperienceSettings = {
    version: 2,
    tonemapping: 'none' | 'linear' | 'filmic' | 'hejl' | 'aces' | 'aces2' | 'neutral',
    highPrecisionRendering: boolean,
    soundUrl?: string,
    background: {
        color: [number, number, number],
        skyboxUrl?: string
    },
    postEffectSettings: PostEffectSettings,
    animTracks: AnimTrack[],
    cameras: Camera[],
    annotations: Annotation[],
    startMode: 'default' | 'animTrack' | 'annotation'
};

type ViewerExportSettings = {
    type: 'html' | 'zip';
    experienceSettings: ExperienceSettings;
    events?: Events;
};

type ProgressFunc = (loaded: number, total: number) => void;

const generatedByString = `Generated by ReSplat ${version}`;

// create a filter for gaussians
class GaussianFilter {
    set: (splat: Splat) => void;
    test: (i: number) => boolean;

    constructor(serializeSettings: SerializeSettings) {
        let splat: Splat = null;
        let state: Uint8Array = null;
        let opacity: Float32Array = null;

        this.set = (s: Splat) => {
            splat = s;
            state = splat.splatData.getProp('state') as Uint8Array;
            opacity = splat.splatData.getProp('opacity') as Float32Array;
        };

        const onlySelected = serializeSettings.selected ?? false;
        const minOpacity = serializeSettings.minOpacity ?? 0;
        const removeInvalid = serializeSettings.removeInvalid ?? false;
        const keepStateData = serializeSettings.keepStateData ?? false;
        const preserveDeleted = serializeSettings.preserveDeleted ?? false;

        // properties where +Infinity and -Infinity are valid values
        const infOk = new Set(['opacity']);
        // properties where -Infinity is a valid value
        const negInfOk = new Set(['scale_0', 'scale_1', 'scale_2']);

        this.test = (i: number) => {
            // splat is deleted, skip unless preserving state data (for index validity)
            // or explicitly preserving deleted gaussians
            if (!keepStateData && !preserveDeleted && (state[i] & State.deleted) !== 0) {
                return false;
            }

            // optionally filter out unselected gaussians
            if (onlySelected && (state[i] !== State.selected)) {
                return false;
            }

            // optionally filter based on opacity
            if (minOpacity > 0 && sigmoid(opacity[i]) < minOpacity) {
                return false;
            }

            if (removeInvalid) {
                const { splatData } = splat;

                // check if any property of the gaussian is NaN/Infinity
                const element = splatData.getElement('vertex');
                for (let k = 0; k < element.properties.length; ++k) {
                    const prop = element.properties[k];
                    const { storage, name } = prop;
                    if (storage && !Number.isFinite(storage[i])) {
                        if (storage[i] === -Infinity && (infOk.has(name) || negInfOk.has(name))) continue;
                        if (storage[i] === Infinity && infOk.has(name)) continue;
                        return false;
                    }
                }
            }

            return true;
        };
    }
}

// count the total number of gaussians given a filter
const countGaussians = (splats: Splat[], filter: GaussianFilter) => {
    return splats.reduce((accum, splat) => {
        filter.set(splat);
        for (let i = 0; i < splat.splatData.numSplats; ++i) {
            accum += filter.test(i) ? 1 : 0;
        }
        return accum;
    }, 0);
};

const getVertexProperties = (splatData: GSplatData) => {
    return new Set<string>(
        splatData.getElement('vertex')
        .properties.filter((p: any) => p.storage)
        .map((p: any) => p.name)
    );
};

const getCommonPropNames = (splats: Splat[]) => {
    let result: Set<string>;

    for (let i = 0; i < splats.length; ++i) {
        const props = getVertexProperties(splats[i].splatData);
        result = i === 0 ? props : new Set([...result].filter(i => props.has(i)));
    }

    return [...result];
};

const getCommonProps = (splats: Splat[]) => {
    const result = new Map<string, Set<string>>();  // map of name->type

    for (let i = 0; i < splats.length; ++i) {
        const properties = splats[i].splatData.getElement('vertex').properties.filter((p: any) => p.storage);
        properties.forEach((p: any) => {
            if (result.has(p.name)) {
                result.get(p.name).add(p.type);
            } else {
                result.set(p.name, new Set([p.type]));
            }
        });
    }

    return [...result].filter(([_, v]) => v.size === 1).map(([name, type]) => {
        return { name, type: type.values().next().value };
    });
};

const shNames = new Array(45).fill('').map((_, i) => `f_rest_${i}`);
const shBandCoeffs = [0, 3, 8, 15];

// determine the number of sh bands present given an object with 'f_rest_*' properties
const calcSHBands = (data: Set<string>) => {
    return { '9': 1, '24': 2, '-1': 3 }[shNames.findIndex(v => !data.has(v))] ?? 0;
};

type DataType = 'char' | 'uchar' | 'short' | 'ushort' | 'int' | 'uint' | 'float' | 'double';

const DataTypeSize = (dataType: DataType) => {
    return {
        char: 1,
        uchar: 1,
        short: 2,
        ushort: 2,
        int: 4,
        uint: 4,
        float: 4,
        double: 8
    }[dataType];
};

const v = new Vec3();
const q = new Quat();

// calculate splat transforms on demand and cache the result for next time
class SplatTransformCache {
    getMat: (index: number) => Mat4;
    getRot: (index: number) => Quat;
    getScale: (index: number) => Vec3;
    getSHRot: (index: number) => SHRotation;

    constructor(splat: Splat, keepWorldTransform = false, skipPlyRotation = false) {
        const transforms = new Map<number, { transformIndex: number, mat: Mat4, rot: Quat, scale: Vec3, shRot: SHRotation }>();
        const indices = splat.transformTexture.getSource() as unknown as Uint32Array;
        const tmpMat = new Mat4();
        const tmpMat3 = new Mat3();
        const tmpQuat = new Quat();

        const getTransform = (index: number) => {
            const transformIndex = indices?.[index] ?? 0;
            let result = transforms.get(transformIndex);
            if (!result) {
                result = { transformIndex, mat: null, rot: null, scale: null, shRot: null };
                transforms.set(transformIndex, result);
            }
            return result;
        };

        this.getMat = (index: number) => {
            const transform = getTransform(index);

            if (!transform.mat) {
                const mat = new Mat4();

                // we must undo the transform we apply at load time to output data
                if (!keepWorldTransform) {
                    if (!skipPlyRotation) {
                        mat.setFromEulerAngles(0, 0, -180);
                    }
                    mat.mul2(mat, splat.entity.getWorldTransform());
                }

                // combine with transform palette matrix
                if (transform.transformIndex > 0) {
                    splat.transformPalette.getTransform(transform.transformIndex, tmpMat);
                    mat.mul2(mat, tmpMat);
                }

                transform.mat = mat;
            }

            return transform.mat;
        };

        this.getRot = (index: number) => {
            const transform = getTransform(index);

            if (!transform.rot) {
                transform.rot = new Quat().setFromMat4(this.getMat(index));
            }

            return transform.rot;
        };

        this.getScale = (index: number) => {
            const transform = getTransform(index);

            if (!transform.scale) {
                const scale = new Vec3();
                this.getMat(index).getScale(scale);
                transform.scale = scale;
            }

            return transform.scale;
        };

        this.getSHRot = (index: number) => {
            const transform = getTransform(index);

            if (!transform.shRot) {
                tmpQuat.setFromMat4(this.getMat(index));
                tmpMat3.setFromQuat(tmpQuat);
                transform.shRot = new SHRotation(tmpMat3);
            }

            return transform.shRot;
        };
    }
}

// helper class for extracting and transforming a single splat's data
// to prepare it for export
class SingleSplat {
    // final data keyed on member name
    data: any = {};

    // read a single gaussian's data and transform it for export
    read: (splats: Splat, i: number) => void;

    // specify the data members required
    constructor(members: string[], serializeSettings: SerializeSettings) {
        const data: any = {};
        members.forEach((name) => {
            data[name] = 0;
        });

        const hasPosition = ['x', 'y', 'z'].every(v => data.hasOwnProperty(v));
        const hasRotation = ['rot_0', 'rot_1', 'rot_2', 'rot_3'].every(v => data.hasOwnProperty(v));
        const hasScale = ['scale_0', 'scale_1', 'scale_2'].every(v => data.hasOwnProperty(v));
        const hasColor = ['f_dc_0', 'f_dc_1', 'f_dc_2'].every(v => data.hasOwnProperty(v));
        const hasOpacity = data.hasOwnProperty('opacity');

        const dstSHBands = calcSHBands(new Set(Object.keys(data)));
        const dstSHCoeffs = shBandCoeffs[dstSHBands];
        const tmpSHData = dstSHBands ? new Float32Array(dstSHCoeffs) : null;

        type CacheEntry = {
            splat: Splat;
            transformCache: SplatTransformCache;
            srcProps: { [name: string]: Float32Array };
            grade: ColorGrade;
        };

        const cacheMap = new Map<Splat, CacheEntry>();
        let cacheEntry: CacheEntry;

        const read = (splat: Splat, i: number) => {
            // get the cached data entry for this splat
            if (splat !== cacheEntry?.splat) {
                if (!cacheMap.has(splat)) {
                    const transformCache = new SplatTransformCache(splat, serializeSettings.keepWorldTransform, serializeSettings.skipPlyRotation);

                    const srcPropNames = getVertexProperties(splat.splatData);
                    const srcSHBands = calcSHBands(srcPropNames);
                    const srcSHCoeffs = shBandCoeffs[srcSHBands];

                    // cache the props objects
                    const srcProps: { [name: string]: Float32Array } = {};

                    members.forEach((name) => {
                        const shIndex = shNames.indexOf(name);
                        if (shIndex >= 0) {
                            const a = Math.floor(shIndex / dstSHCoeffs);
                            const b = shIndex % dstSHCoeffs;
                            srcProps[name] = (b < srcSHCoeffs) ? splat.splatData.getProp(shNames[a * srcSHCoeffs + b]) as Float32Array : null;
                        } else {
                            srcProps[name] = splat.splatData.getProp(name) as Float32Array;
                        }
                    });

                    const grade = new ColorGrade(splat);

                    cacheEntry = { splat, transformCache, srcProps, grade };

                    cacheMap.set(splat, cacheEntry);
                } else {
                    cacheEntry = cacheMap.get(splat);
                }
            }

            const { transformCache, srcProps, grade } = cacheEntry;

            // copy members
            members.forEach((name) => {
                data[name] = srcProps[name]?.[i] ?? 0;
            });

            // apply transform palette transforms
            const mat = transformCache.getMat(i);

            if (hasPosition) {
                v.set(data.x, data.y, data.z);
                mat.transformPoint(v, v);
                [data.x, data.y, data.z] = [v.x, v.y, v.z];
            }

            if (hasRotation) {
                const quat = transformCache.getRot(i);
                q.set(data.rot_1, data.rot_2, data.rot_3, data.rot_0).mul2(quat, q);
                [data.rot_1, data.rot_2, data.rot_3, data.rot_0] = [q.x, q.y, q.z, q.w];
            }

            if (hasScale) {
                const scale = transformCache.getScale(i);
                data.scale_0 = Math.log(Math.exp(data.scale_0) * scale.x);
                data.scale_1 = Math.log(Math.exp(data.scale_1) * scale.y);
                data.scale_2 = Math.log(Math.exp(data.scale_2) * scale.z);
            }

            if (dstSHBands > 0) {
                for (let c = 0; c < 3; ++c) {
                    for (let d = 0; d < dstSHCoeffs; ++d) {
                        tmpSHData[d] = data[shNames[c * dstSHCoeffs + d]];
                    }

                    transformCache.getSHRot(i).apply(tmpSHData);

                    for (let d = 0; d < dstSHCoeffs; ++d) {
                        data[shNames[c * dstSHCoeffs + d]] = tmpSHData[d];
                    }
                }
            }

            if (!serializeSettings.keepColorTint && hasColor && grade.hasTint) {
                const c = {
                    r: dcDecode(data.f_dc_0),
                    g: dcDecode(data.f_dc_1),
                    b: dcDecode(data.f_dc_2)
                };

                grade.applyDC(c);
                data.f_dc_0 = dcEncode(c.r);
                data.f_dc_1 = dcEncode(c.g);
                data.f_dc_2 = dcEncode(c.b);

                if (dstSHBands > 0) {
                    for (let d = 0; d < dstSHCoeffs; ++d) {
                        c.r = data[shNames[d]];
                        c.g = data[shNames[d + dstSHCoeffs]];
                        c.b = data[shNames[d + dstSHCoeffs * 2]];

                        grade.applySH(c);
                        data[shNames[d]] = c.r;
                        data[shNames[d + dstSHCoeffs]] = c.g;
                        data[shNames[d + dstSHCoeffs * 2]] = c.b;
                    }
                }
            }

            if (!serializeSettings.keepColorTint && hasOpacity && splat.transparency !== 1) {
                data.opacity = grade.applyOpacity(data.opacity);
            }
        };

        this.data = data;
        this.read = read;
    }
}

const serializePlyToWriter = async (splats: Splat[], serializeSettings: SerializeSettings, writer: Writer, progress?: ProgressFunc): Promise<void> => {
    const { maxSHBands, keepStateData } = serializeSettings;

    // create filter and count total gaussians
    const filter = new GaussianFilter(serializeSettings);
    const totalGaussians = countGaussians(splats, filter);
    if (totalGaussians === 0) {
        return;
    }

    // this data is filtered out, as it holds internal editor state
    const internalProps = keepStateData ? ['transform'] : ['state', 'transform'];

    const props = getCommonProps(splats)
    // filter out internal props
    .filter(p => !internalProps.includes(p.name))
    // filter out max SH bands
    .filter((p) => {
        if (!p.name.startsWith('f_rest_')) {
            return true;
        }
        const i = parseInt(p.name.slice(7), 10);
        return i < [0, 9, 24, 45][maxSHBands ?? 3];
    });

    const headerText = [
        'ply',
        'format binary_little_endian 1.0',
        // FIXME: disable for now due to other tooling not supporting any header
        // `comment ${generatedByString}`,
        `element vertex ${totalGaussians}`,
        props.map(p => `property ${p.type} ${p.name}`),
        'end_header',
        ''
    ].flat().join('\n');

    const singleSplat = new SingleSplat(props.map(p => p.name), serializeSettings);

    const gaussianSizeBytes = props.reduce((tot, p) => tot + DataTypeSize(p.type as DataType), 0);

    const buf = new Uint8Array(1024 * gaussianSizeBytes);
    const dataView = new DataView(buf.buffer);
    let offset = 0;

    const header = new TextEncoder().encode(headerText);

    // construct a progress writer over the writer
    const progressWriter = new ProgressWriter(writer, header.byteLength + totalGaussians * gaussianSizeBytes, progress);

    // write encoded header
    await progressWriter.write(header);

    for (let e = 0; e < splats.length; ++e) {
        const splat = splats[e];
        const { splatData } = splat;
        filter.set(splat);

        for (let i = 0; i < splatData.numSplats; ++i) {
            if (!filter.test(i)) continue;

            singleSplat.read(splat, i);

            // write
            for (let j = 0; j < props.length; ++j) {
                if (props[j].type === 'uchar') {
                    dataView.setUint8(offset, singleSplat.data[props[j].name]);
                    offset += 1;
                } else {
                    dataView.setFloat32(offset, singleSplat.data[props[j].name], true);
                    offset += 4;
                }
            }

            // buffer is full, write it to the output stream
            if (offset === buf.byteLength) {
                await progressWriter.write(buf);
                offset = 0;
            }
        }
    }

    // write the last (most likely partially filled) buf
    if (offset > 0) {
        await progressWriter.write(new Uint8Array(buf.buffer, 0, offset));
    }

    progressWriter.close();
};

const serializePly = async (splats: Splat[], serializeSettings: SerializeSettings, fs: FileSystem, filename = 'output.ply', progress?: ProgressFunc): Promise<void> => {
    const writer = await fs.createWriter(filename);
    await serializePlyToWriter(splats, serializeSettings, writer, progress);
    await writer.close();
};

// Standard PLY format: 62 properties in a specific order
// This format is compatible with most Gaussian Splat renderers
const STANDARD_PLY_PROPERTIES = [
    // Position (3)
    'x', 'y', 'z',
    // Normals (3) - filled with 0 if missing
    'nx', 'ny', 'nz',
    // Spherical Harmonics DC (3)
    'f_dc_0', 'f_dc_1', 'f_dc_2',
    // Spherical Harmonics Rest (45) - filled with 0 if missing
    ...new Array(45).fill('').map((_, i) => `f_rest_${i}`),
    // Opacity (1)
    'opacity',
    // Scale (3)
    'scale_0', 'scale_1', 'scale_2',
    // Rotation (4)
    'rot_0', 'rot_1', 'rot_2', 'rot_3'
];

const serializeStandardPly = async (splats: Splat[], serializeSettings: SerializeSettings, fs: FileSystem, filename = 'output.ply', progress?: ProgressFunc): Promise<void> => {
    const { maxSHBands } = serializeSettings;

    // create filter and count total gaussians
    const filter = new GaussianFilter(serializeSettings);
    const totalGaussians = countGaussians(splats, filter);
    if (totalGaussians === 0) {
        return;
    }

    // Determine which f_rest properties to include based on maxSHBands
    const maxSHCoeffs = [0, 9, 24, 45][maxSHBands ?? 3];

    // Build properties list - always include all standard properties
    // but respect maxSHBands for f_rest
    const props: { name: string; type: string }[] = [];
    for (const name of STANDARD_PLY_PROPERTIES) {
        // Check if this is an f_rest property beyond our band limit
        if (name.startsWith('f_rest_')) {
            const idx = parseInt(name.slice(7), 10);
            if (idx >= maxSHCoeffs) {
                continue; // Skip f_rest beyond selected bands
            }
        }
        props.push({ name, type: 'float' });
    }

    // Build header
    const headerText = [
        'ply',
        'format binary_little_endian 1.0',
        `element vertex ${totalGaussians}`,
        props.map(p => `property ${p.type} ${p.name}`),
        'end_header',
        ''
    ].flat().join('\n');

    // Get the property names that exist in the source data
    const commonPropNames = new Set(getCommonPropNames(splats));

    // Create SingleSplat reader for properties that exist in source
    // We need to request all properties we want to read
    const propsToRead = props.map(p => p.name).filter((name) => {
        // Always try to read these core properties
        if (['x', 'y', 'z', 'f_dc_0', 'f_dc_1', 'f_dc_2', 'opacity',
            'scale_0', 'scale_1', 'scale_2',
            'rot_0', 'rot_1', 'rot_2', 'rot_3'].includes(name)) {
            return true;
        }
        // For normals and f_rest, only read if they exist
        return commonPropNames.has(name);
    });

    const singleSplat = new SingleSplat(propsToRead, serializeSettings);

    const gaussianSizeBytes = props.length * 4; // all properties are float32

    const buf = new Uint8Array(1024 * gaussianSizeBytes);
    const dataView = new DataView(buf.buffer);
    let offset = 0;

    const header = new TextEncoder().encode(headerText);

    // create writer from filesystem
    const writer = await fs.createWriter(filename);

    // construct a progress writer over the writer
    const progressWriter = new ProgressWriter(writer, header.byteLength + totalGaussians * gaussianSizeBytes, progress);

    // write encoded header
    await progressWriter.write(header);

    for (let e = 0; e < splats.length; ++e) {
        const splat = splats[e];
        const { splatData } = splat;
        filter.set(splat);

        for (let i = 0; i < splatData.numSplats; ++i) {
            if (!filter.test(i)) continue;

            singleSplat.read(splat, i);

            // write all properties in standard order
            for (let j = 0; j < props.length; ++j) {
                const propName = props[j].name;
                // Use value from source if available, otherwise 0
                const value = Object.prototype.hasOwnProperty.call(singleSplat.data, propName) ? singleSplat.data[propName] : 0;
                dataView.setFloat32(offset, value, true);
                offset += 4;
            }

            // buffer is full, write it to the output stream
            if (offset === buf.byteLength) {
                await progressWriter.write(buf);
                offset = 0;
            }
        }
    }

    // write the last (most likely partially filled) buf
    if (offset > 0) {
        await progressWriter.write(new Uint8Array(buf.buffer, 0, offset));
    }

    progressWriter.close();
    await writer.close();
};

interface CompressedIndex {
    splatIndex: number;
    i: number;
    globalIndex: number;
}

// process and compress a chunk of 256 splats
class Chunk {
    static members = [
        'x', 'y', 'z',
        'scale_0', 'scale_1', 'scale_2',
        'f_dc_0', 'f_dc_1', 'f_dc_2', 'opacity',
        'rot_0', 'rot_1', 'rot_2', 'rot_3'
    ];

    size: number;
    data: any = {};

    // compressed data
    position: Uint32Array;
    rotation: Uint32Array;
    scale: Uint32Array;
    color: Uint32Array;

    constructor(size = 256) {
        this.size = size;
        Chunk.members.forEach((m) => {
            this.data[m] = new Float32Array(size);
        });
        this.position = new Uint32Array(size);
        this.rotation = new Uint32Array(size);
        this.scale = new Uint32Array(size);
        this.color = new Uint32Array(size);
    }

    set(index: number, splat: SingleSplat) {
        Chunk.members.forEach((name) => {
            this.data[name][index] = splat.data[name];
        });
    }

    pack() {
        const calcMinMax = (data: Float32Array) => {
            let min;
            let max;
            min = max = data[0];
            for (let i = 1; i < data.length; ++i) {
                const v = data[i];
                min = Math.min(min, v);
                max = Math.max(max, v);
            }
            return { min, max };
        };

        const normalize = (x: number, min: number, max: number) => {
            if (x <= min) return 0;
            if (x >= max) return 1;
            return (max - min < 0.00001) ? 0 : (x - min) / (max - min);
        };

        const data = this.data;

        const x = data.x;
        const y = data.y;
        const z = data.z;
        const scale_0 = data.scale_0;
        const scale_1 = data.scale_1;
        const scale_2 = data.scale_2;
        const rot_0 = data.rot_0;
        const rot_1 = data.rot_1;
        const rot_2 = data.rot_2;
        const rot_3 = data.rot_3;
        const f_dc_0 = data.f_dc_0;
        const f_dc_1 = data.f_dc_1;
        const f_dc_2 = data.f_dc_2;
        const opacity = data.opacity;

        const px = calcMinMax(x);
        const py = calcMinMax(y);
        const pz = calcMinMax(z);

        const sx = calcMinMax(scale_0);
        const sy = calcMinMax(scale_1);
        const sz = calcMinMax(scale_2);

        // clamp scale because sometimes values are at infinity
        const clamp = (v: number, min: number, max: number) => Math.max(min, Math.min(max, v));
        sx.min = clamp(sx.min, -20, 20);
        sx.max = clamp(sx.max, -20, 20);
        sy.min = clamp(sy.min, -20, 20);
        sy.max = clamp(sy.max, -20, 20);
        sz.min = clamp(sz.min, -20, 20);
        sz.max = clamp(sz.max, -20, 20);

        // convert f_dc_ to colors before calculating min/max and packaging
        for (let i = 0; i < f_dc_0.length; ++i) {
            f_dc_0[i] = dcDecode(f_dc_0[i]);
            f_dc_1[i] = dcDecode(f_dc_1[i]);
            f_dc_2[i] = dcDecode(f_dc_2[i]);
        }

        const cr = calcMinMax(f_dc_0);
        const cg = calcMinMax(f_dc_1);
        const cb = calcMinMax(f_dc_2);

        const packUnorm = (value: number, bits: number) => {
            const t = (1 << bits) - 1;
            return Math.max(0, Math.min(t, Math.floor(value * t + 0.5)));
        };

        const pack111011 = (x: number, y: number, z: number) => {
            return packUnorm(x, 11) << 21 |
                   packUnorm(y, 10) << 11 |
                   packUnorm(z, 11);
        };

        const pack8888 = (x: number, y: number, z: number, w: number) => {
            return packUnorm(x, 8) << 24 |
                   packUnorm(y, 8) << 16 |
                   packUnorm(z, 8) << 8 |
                   packUnorm(w, 8);
        };

        // pack quaternion into 2,10,10,10
        const packRot = (x: number, y: number, z: number, w: number) => {
            q.set(x, y, z, w).normalize();
            const a = [q.x, q.y, q.z, q.w];
            const largest = a.reduce((curr, v, i) => (Math.abs(v) > Math.abs(a[curr]) ? i : curr), 0);

            if (a[largest] < 0) {
                a[0] = -a[0];
                a[1] = -a[1];
                a[2] = -a[2];
                a[3] = -a[3];
            }

            const norm = Math.sqrt(2) * 0.5;
            let result = largest;
            for (let i = 0; i < 4; ++i) {
                if (i !== largest) {
                    result = (result << 10) | packUnorm(a[i] * norm + 0.5, 10);
                }
            }

            return result;
        };

        // pack
        for (let i = 0; i < this.size; ++i) {
            this.position[i] = pack111011(
                normalize(x[i], px.min, px.max),
                normalize(y[i], py.min, py.max),
                normalize(z[i], pz.min, pz.max)
            );

            this.rotation[i] = packRot(rot_0[i], rot_1[i], rot_2[i], rot_3[i]);

            this.scale[i] = pack111011(
                normalize(scale_0[i], sx.min, sx.max),
                normalize(scale_1[i], sy.min, sy.max),
                normalize(scale_2[i], sz.min, sz.max)
            );

            this.color[i] = pack8888(
                normalize(f_dc_0[i], cr.min, cr.max),
                normalize(f_dc_1[i], cg.min, cg.max),
                normalize(f_dc_2[i], cb.min, cb.max),
                1 / (1 + Math.exp(-opacity[i]))
            );
        }

        return { px, py, pz, sx, sy, sz, cr, cg, cb };
    }
}

// sort the compressed indices into morton order
const sortSplats = (splats: Splat[], indices: CompressedIndex[]) => {
    // https://fgiesen.wordpress.com/2009/12/13/decoding-morton-codes/
    const encodeMorton3 = (x: number, y: number, z: number) : number => {
        const Part1By2 = (x: number) => {
            x &= 0x000003ff;
            x = (x ^ (x << 16)) & 0xff0000ff;
            x = (x ^ (x <<  8)) & 0x0300f00f;
            x = (x ^ (x <<  4)) & 0x030c30c3;
            x = (x ^ (x <<  2)) & 0x09249249;
            return x;
        };

        return (Part1By2(z) << 2) + (Part1By2(y) << 1) + Part1By2(x);
    };

    let minx: number;
    let miny: number;
    let minz: number;
    let maxx: number;
    let maxy: number;
    let maxz: number;

    // calculate scene extents across all splats (using sort centers, because they're in world space)
    for (let i = 0; i < splats.length; ++i) {
        const splat = splats[i];
        const splatData = splat.splatData;
        const state = splatData.getProp('state') as Uint8Array;
        const { centers } = splat.entity.gsplat.instance.sorter;

        for (let i = 0; i < splatData.numSplats; ++i) {
            if ((state[i] & State.deleted) === 0) {
                const x = centers[i * 3 + 0];
                const y = centers[i * 3 + 1];
                const z = centers[i * 3 + 2];

                if (minx === undefined) {
                    minx = maxx = x;
                    miny = maxy = y;
                    minz = maxz = z;
                } else {
                    if (x < minx) minx = x; else if (x > maxx) maxx = x;
                    if (y < miny) miny = y; else if (y > maxy) maxy = y;
                    if (z < minz) minz = z; else if (z > maxz) maxz = z;
                }
            }
        }
    }

    const xlen = maxx - minx;
    const ylen = maxy - miny;
    const zlen = maxz - minz;

    const morton = new Uint32Array(indices.length);
    let idx = 0;
    for (let i = 0; i < splats.length; ++i) {
        const splat = splats[i];
        const splatData = splat.splatData;
        const state = splatData.getProp('state') as Uint8Array;
        const { centers } = splat.entity.gsplat.instance.sorter;

        for (let i = 0; i < splatData.numSplats; ++i) {
            if ((state[i] & State.deleted) === 0) {
                const x = centers[i * 3 + 0];
                const y = centers[i * 3 + 1];
                const z = centers[i * 3 + 2];

                const ix = Math.min(1023, Math.floor(1024 * (x - minx) / xlen));
                const iy = Math.min(1023, Math.floor(1024 * (y - miny) / ylen));
                const iz = Math.min(1023, Math.floor(1024 * (z - minz) / zlen));

                morton[idx++] = encodeMorton3(ix, iy, iz);
            }
        }
    }

    // order splats by morton code
    indices.sort((a, b) => morton[a.globalIndex] - morton[b.globalIndex]);
};

const serializePlyCompressed = async (splats: Splat[], options: SerializeSettings, fs: FileSystem, progress?: ProgressFunc): Promise<void> => {
    const { maxSHBands } = options;

    // create filter and count total gaussians
    const filter = new GaussianFilter(options);

    // make a list of indices spanning all splats (so we can sort them together)
    const indices: CompressedIndex[] = [];
    for (let splatIndex = 0; splatIndex < splats.length; ++splatIndex) {
        const splatData = splats[splatIndex].splatData;
        filter.set(splats[splatIndex]);
        for (let i = 0; i < splatData.numSplats; ++i) {
            if (filter.test(i)) {
                indices.push({ splatIndex, i, globalIndex: indices.length });
            }
        }
    }

    if (indices.length === 0) {
        console.error('nothing to export');
        return;
    }

    // create writer from filesystem
    const writer = await fs.createWriter('output.compressed.ply');

    const numSplats = indices.length;
    const numChunks = Math.ceil(numSplats / 256);

    const chunkProps = [
        'min_x', 'min_y', 'min_z',
        'max_x', 'max_y', 'max_z',
        'min_scale_x', 'min_scale_y', 'min_scale_z',
        'max_scale_x', 'max_scale_y', 'max_scale_z',
        'min_r', 'min_g', 'min_b',
        'max_r', 'max_g', 'max_b'
    ];

    const vertexProps = [
        'packed_position',
        'packed_rotation',
        'packed_scale',
        'packed_color'
    ];

    // calculate the number of output bands given the scene splat data and
    // user-chosen maxSHBands
    const outputSHBands = (() => {
        const splatBands = splats.map(s => calcSHBands(getVertexProperties(s.splatData)));
        return Math.min(maxSHBands ?? 3, Math.max(...splatBands));
    })();
    const outputSHCoeffs = shBandCoeffs[outputSHBands];

    const shHeader = outputSHBands ? [
        `element sh ${numSplats}`,
        new Array(outputSHCoeffs * 3).fill('').map((_, i) => `property uchar f_rest_${i}`)
    ].flat() : [];

    const headerText = [
        'ply',
        'format binary_little_endian 1.0',
        `comment ${generatedByString}`,
        `element chunk ${numChunks}`,
        chunkProps.map(p => `property float ${p}`),
        `element vertex ${numSplats}`,
        vertexProps.map(p => `property uint ${p}`),
        shHeader,
        'end_header\n'
    ].flat().join('\n');

    // sort splats into some kind of order (morton order rn)
    sortSplats(splats, indices);

    const singleSplat = new SingleSplat([
        'x', 'y', 'z',
        'scale_0', 'scale_1', 'scale_2',
        'f_dc_0', 'f_dc_1', 'f_dc_2', 'opacity',
        'rot_0', 'rot_1', 'rot_2', 'rot_3'
    ], options);

    const prepareChunk = (chunk: Chunk, i: number) => {
        const num = Math.min(numSplats, (i + 1) * 256) - i * 256;

        for (let j = 0; j < num; ++j) {
            const index = indices[i * 256 + j];

            // read splat
            singleSplat.read(splats[index.splatIndex], index.i);

            // update chunk
            chunk.set(j, singleSplat);
        }

        // pad the end of the last chunk with duplicate data
        if (num < 256) {
            for (let j = num; j < 256; ++j) {
                chunk.set(j, singleSplat);
            }
        }
    };

    const header = new TextEncoder().encode(headerText);

    const totalBytes =
        header.byteLength +
        numChunks * chunkProps.length * 4 +
        numSplats * vertexProps.length * 4 +
        outputSHCoeffs * 3 * numSplats;

    const progressWriter = new ProgressWriter(writer, totalBytes, progress);

    // write the header
    await progressWriter.write(header);

    const chunk = new Chunk();

    // write chunks
    const chunkData = new Float32Array(18);
    const chunkDataUint8 = new Uint8Array(chunkData.buffer);
    for (let i = 0; i < numChunks; ++i) {
        prepareChunk(chunk, i);

        const result = chunk.pack();

        chunkData[0] = result.px.min;
        chunkData[1] = result.py.min;
        chunkData[2] = result.pz.min;
        chunkData[3] = result.px.max;
        chunkData[4] = result.py.max;
        chunkData[5] = result.pz.max;

        chunkData[6] = result.sx.min;
        chunkData[7] = result.sy.min;
        chunkData[8] = result.sz.min;
        chunkData[9] = result.sx.max;
        chunkData[10] = result.sy.max;
        chunkData[11] = result.sz.max;

        chunkData[12] = result.cr.min;
        chunkData[13] = result.cg.min;
        chunkData[14] = result.cb.min;
        chunkData[15] = result.cr.max;
        chunkData[16] = result.cg.max;
        chunkData[17] = result.cb.max;

        await progressWriter.write(chunkDataUint8);
    }

    // write vertices
    const vertexData = new Uint32Array(256 * 4);
    const vertexDataUint8 = new Uint8Array(vertexData.buffer);
    for (let i = 0; i < numChunks; ++i) {
        const num = Math.min(numSplats, (i + 1) * 256) - i * 256;

        prepareChunk(chunk, i);
        chunk.pack();

        // write vertex data
        for (let j = 0; j < num; ++j) {
            vertexData[j * 4 + 0] = chunk.position[j];
            vertexData[j * 4 + 1] = chunk.rotation[j];
            vertexData[j * 4 + 2] = chunk.scale[j];
            vertexData[j * 4 + 3] = chunk.color[j];
        }

        await progressWriter.write(num === 256 ? vertexDataUint8 : new Uint8Array(vertexData.buffer, 0, num * 4 * 4));
    }

    // write sh
    const singleSplatSH = new SingleSplat(shNames.slice(0, outputSHCoeffs * 3), options);

    const shData = new Uint8Array(outputSHCoeffs * 3 * 256);
    for (let i = 0; i < numChunks; ++i) {
        const num = Math.min(numSplats, (i + 1) * 256) - i * 256;

        for (let j = 0; j < num; ++j) {
            const index = indices[i * 256 + j];

            // read splat
            singleSplatSH.read(splats[index.splatIndex], index.i);

            // quantize and write sh data
            const offset = j * outputSHCoeffs * 3;
            for (let k = 0; k < outputSHCoeffs * 3; ++k) {
                const nvalue = singleSplatSH.data[shNames[k]] / 8 + 0.5;
                shData[offset + k] = Math.max(0, Math.min(255, Math.trunc(nvalue * 256)));
            }
        }

        await progressWriter.write(num === 256 ? shData : new Uint8Array(shData.buffer, 0, num * outputSHCoeffs * 3));
    }

    progressWriter.close();
    await writer.close();
};

const serializeSplat = async (splats: Splat[], options: SerializeSettings, fs: FileSystem): Promise<void> => {
    // create writer from filesystem
    const writer = await fs.createWriter('output.splat');
    // create filter and count total gaussians
    const filter = new GaussianFilter(options);
    const totalGaussians = countGaussians(splats, filter);
    if (totalGaussians === 0) {
        return;
    }

    // position.xyz: float32, scale.xyz: float32, color.rgba: uint8, quaternion.ijkl: uint8
    const result = new Uint8Array(totalGaussians * 32);
    const dataView = new DataView(result.buffer);

    let idx = 0;

    const props = ['x', 'y', 'z', 'opacity', 'rot_0', 'rot_1', 'rot_2', 'rot_3', 'f_dc_0', 'f_dc_1', 'f_dc_2', 'scale_0', 'scale_1', 'scale_2'];
    const singleSplat = new SingleSplat(props, options);
    const { data } = singleSplat;

    const clamp = (x: number) => Math.max(0, Math.min(255, x));

    for (let e = 0; e < splats.length; ++e) {
        const splat = splats[e];
        const { splatData } = splat;
        filter.set(splat);

        for (let i = 0; i < splatData.numSplats; ++i) {
            if (!filter.test(i)) continue;

            singleSplat.read(splat, i);

            const off = idx++ * 32;

            dataView.setFloat32(off + 0, data.x, true);
            dataView.setFloat32(off + 4, data.y, true);
            dataView.setFloat32(off + 8, data.z, true);

            dataView.setFloat32(off + 12, Math.exp(data.scale_0), true);
            dataView.setFloat32(off + 16, Math.exp(data.scale_1), true);
            dataView.setFloat32(off + 20, Math.exp(data.scale_2), true);

            dataView.setUint8(off + 24, clamp(dcDecode(data.f_dc_0) * 255));
            dataView.setUint8(off + 25, clamp(dcDecode(data.f_dc_1) * 255));
            dataView.setUint8(off + 26, clamp(dcDecode(data.f_dc_2) * 255));
            dataView.setUint8(off + 27, clamp(sigmoid(data.opacity) * 255));

            dataView.setUint8(off + 28, clamp(data.rot_0 * 128 + 128));
            dataView.setUint8(off + 29, clamp(data.rot_1 * 128 + 128));
            dataView.setUint8(off + 30, clamp(data.rot_2 * 128 + 128));
            dataView.setUint8(off + 31, clamp(data.rot_3 * 128 + 128));
        }
    }

    await writer.write(result);
    await writer.close();
};

// Cached WebGPU device for SOG compression
let cachedGpuDevice: WebgpuGraphicsDevice | null = null;
let cachedBackbuffer: Texture | null = null;

// Configure splat-transform's worker/WASM loading for the bundled Electron
// environment. The rollup bundle inlines splat-transform's JS into dist/index.js,
// but the worker script (dist/worker.mjs) and WASM binary (lib/webp.wasm) are
// separate assets that splat-transform auto-resolves via `import.meta.url`.
// In Electron the app loads from file:// — module workers cannot be spawned
// from file:// (CORS), and the auto-resolved WASM path (../lib/webp.wasm
// relative to the bundle) does not exist. This would cause the WorkerQueue
// slot to hang forever in 'starting' state (onerror never fires for file://
// module-worker failures), stalling the entire SOG encode pipeline.
//
// Fix: (1) force inline mode so no worker is spawned, and (2) point the WASM
// URL at the webp.wasm asset that rollup copies into dist/ alongside index.js.
let splatTransformConfigured = false;
const configureSplatTransform = () => {
    if (splatTransformConfigured) return;
    splatTransformConfigured = true;

    // Force all CPU-heavy tasks (WebP encode, quantize1d) to run inline on the
    // calling thread. This is slower than worker parallelism but is the only
    // mode that works reliably under file:// in Electron.
    WorkerQueue.maxWorkers = 0;

    // Resolve webp.wasm relative to this module (dist/index.js after bundling).
    // rollup.config.mjs copies the wasm into dist/ alongside the bundle.
    try {
        WebPCodec.wasmUrl = new URL('./webp.wasm', import.meta.url).toString();
    } catch {
        // import.meta.url may be unavailable in some non-module contexts; leave
        // the default and let splat-transform's own resolution attempt run.
    }
};

const createGpuDevice = async (): Promise<WebgpuGraphicsDevice> => {
    configureSplatTransform();

    if (cachedGpuDevice) {
        return cachedGpuDevice;
    }

    if (!navigator.gpu) {
        throw new Error('WebGPU is not available in this browser');
    }

    // Create a minimal canvas for the graphics device
    const canvas = document.createElement('canvas');
    canvas.width = 1024;
    canvas.height = 512;

    const graphicsDevice = new WebgpuGraphicsDevice(canvas, {
        antialias: false,
        depth: false,
        stencil: false
    });

    await graphicsDevice.createDevice();

    // Create external backbuffer (required by PlayCanvas)
    cachedBackbuffer = new Texture(graphicsDevice, {
        width: 1024,
        height: 512,
        name: 'SogComputeBackbuffer',
        mipmaps: false,
        format: PIXELFORMAT_BGRA8
    });

    // @ts-ignore - externalBackbuffer is an internal property
    graphicsDevice.externalBackbuffer = cachedBackbuffer;

    cachedGpuDevice = graphicsDevice;
    return graphicsDevice;
};

/**
 * Extract Splat data into a DataTable for use with splat-transform writers.
 * This is shared between serializeSog and serializeViewer.
 */
const extractDataTable = (splats: Splat[], settings: SerializeSettings): DataTable => {
    const { maxSHBands = 3 } = settings;

    // Determine which members to extract
    const shCoeffs = [0, 3, 8, 15][maxSHBands];
    const memberNames = [
        'x', 'y', 'z',
        'scale_0', 'scale_1', 'scale_2',
        'f_dc_0', 'f_dc_1', 'f_dc_2', 'opacity',
        'rot_0', 'rot_1', 'rot_2', 'rot_3',
        ...shNames.slice(0, shCoeffs * 3)
    ];

    // Create SingleSplat for data extraction
    const singleSplat = new SingleSplat(memberNames, settings);

    // Create filter
    const filter = new GaussianFilter(settings);

    // Count total gaussians to export
    let totalCount = 0;
    for (const splat of splats) {
        filter.set(splat);
        for (let i = 0; i < splat.splatData.numSplats; ++i) {
            if (filter.test(i)) {
                totalCount++;
            }
        }
    }

    if (totalCount === 0) {
        throw new Error('No gaussians to export');
    }

    // Create DataTable columns. Tag the table with Transform.PLY because
    // SingleSplat.read pre-applies the PLY-style 180° Z flip (see
    // SplatTransformCache.getMat), so the column data is in PLY space.
    // Without this, splat-transform writers (writeSog, writeHtml) would apply
    // the flip a second time and produce upside-down output.
    const columns = memberNames.map(name => new Column(name, new Float32Array(totalCount)));
    const dataTable = new DataTable(columns, Transform.PLY);

    // Extract data into DataTable
    let idx = 0;
    for (const splat of splats) {
        filter.set(splat);
        for (let i = 0; i < splat.splatData.numSplats; ++i) {
            if (!filter.test(i)) continue;

            singleSplat.read(splat, i);

            for (let j = 0; j < memberNames.length; ++j) {
                (columns[j].data as Float32Array)[idx] = singleSplat.data[memberNames[j]] ?? 0;
            }
            idx++;
        }
    }

    return dataTable;
};

// Bridge splat-transform progress events to ReSplat's events.
const createProgressRenderer = (header: string, events?: Events): Renderer => ({
    handle: (event: LogEvent) => {
        switch (event.kind) {
            case 'scopeStart':
                if (event.depth === 0) {
                    events?.fire('progressStart', header);
                } else {
                    events?.fire('progressUpdate', {
                        text: event.index !== undefined && event.total !== undefined ?
                            `Step ${event.index} of ${event.total}: ${event.name}` :
                            event.name,
                        progress: 0
                    });
                }
                break;
            case 'scopeEnd':
                if (event.depth === 0) {
                    events?.fire('progressEnd');
                }
                break;
            case 'barStart':
                events?.fire('progressUpdate', { text: event.name, progress: 0 });
                break;
            case 'barTick':
                events?.fire('progressUpdate', {
                    progress: event.total > 0 ? 100 * event.current / event.total : 0
                });
                break;
            case 'barEnd':
                events?.fire('progressUpdate', { progress: 100 });
                break;
            case 'message':
                if (event.level === 'error') console.error(event.text);
                else if (event.level === 'warn') console.warn(event.text);
                else if (event.level === 'info') console.info(event.text);
                else if (event.level === 'debug') console.debug(event.text);
                break;
            case 'output':
                console.log(event.text);
                break;
        }
    }
});

const serializeViewer = async (splats: Splat[], serializeSettings: SerializeSettings, options: ViewerExportSettings, fs: FileSystem): Promise<void> => {
    const { experienceSettings, events } = options;

    configureSplatTransform();
    splatTransformLogger.setRenderer(createProgressRenderer('Exporting HTML', events));

    // Extract splat data to DataTable
    const dataTable = extractDataTable(splats, serializeSettings);

    // splat-transform's writers leave their top-level scope open on error
    // (their contract is for the caller to unwind), so we explicitly
    // unwind here to deliver a matching depth-0 `scopeEnd(failed)` to the
    // renderer. That fires `progressEnd` and dismisses the dialog before
    // any error popup is shown.
    try {
        if (options.type === 'html') {
            // Bundled HTML - writeHtml handles everything
            await writeHtml({
                filename: 'output.html',
                dataTable,
                viewerSettingsJson: experienceSettings,
                bundle: true,
                iterations: 10,
                createDevice: createGpuDevice
            }, fs);
        } else {
            // Package - use unbundled mode into a MemoryFileSystem, then ZIP
            const memFs = new MemoryFileSystem();
            await writeHtml({
                filename: 'index.html',
                dataTable,
                viewerSettingsJson: experienceSettings,
                bundle: false,
                iterations: 10,
                createDevice: createGpuDevice
            }, memFs);

            // Create ZIP from memory filesystem results. The try/finally
            // ensures zipFs (and its underlying writer) is closed even if a
            // write throws partway through, so we don't leak the output file.
            const zipWriter = await fs.createWriter('output.zip');
            const zipFs = new ZipFileSystem(zipWriter);
            try {
                for (const [filename, data] of memFs.results.entries()) {
                    const writer = await zipFs.createWriter(filename);
                    await writer.write(data);
                    await writer.close();
                }
            } finally {
                await zipFs.close();
            }
        }
    } catch (err) {
        splatTransformLogger.unwindAll(true);
        throw err;
    }
};

// SOG serialization using splat-transform library

type SogSettings = SerializeSettings & {
    iterations: number;
    events?: Events;
    filename?: string;
};

// LCC2 (Lixel CyberColor 2) directory-format export options. Phase 1 exercises
// a single LOD with splatType='.sog'; lodLevels>1 and splatType='.spz' are
// reserved for Phase 2 (LOD auto-generation) and treated as 1/'.sog' here.
type Lcc2ExportOptions = {
    name: string;                          // scene/file base name (no extension)
    splatIdx?: number[] | null;            // selected splat indices into the splats array
    serializeSettings: SogSettings;        // reuse serializeSog's settings (maxSHBands, iterations, events, ...)
    lodLevels?: number;                    // default 1 (Phase 1; >1 reserved for Phase 2, treated as 1)
    splatType?: '.sog' | '.spz';           // default '.sog' (Phase 1 only '.sog' is exercised)
};

const serializeSog = async (splats: Splat[], settings: SogSettings, fs: FileSystem): Promise<void> => {
    const { iterations = 10, events, filename = 'output.sog' } = settings;

    configureSplatTransform();
    splatTransformLogger.setRenderer(createProgressRenderer('Exporting SOG', events));

    // Extract splat data to DataTable
    const dataTable = extractDataTable(splats, settings);

    // splat-transform's writers leave their top-level scope open on error
    // (their contract is for the caller to unwind), so we explicitly
    // unwind here to deliver a matching depth-0 `scopeEnd(failed)` to the
    // renderer. That fires `progressEnd` and dismisses the dialog before
    // any error popup is shown.
    try {
        await writeSogInternal({
            filename,
            dataTable,
            bundle: true,
            iterations,
            createDevice: createGpuDevice
        }, fs);
    } catch (err) {
        splatTransformLogger.unwindAll(true);
        throw err;
    }
};

// Apply the PLY→LCC2 coordinate conversion in-place on a PLY-space DataTable.
//
// writeSog always encodes in PLY space (bakeTransform → Z(180) rotation).
// readLcc2Source applies LCC2_TRANSFORM = fromEulers(90, 0, 180) on top of
// the PLY-space SOG data. Without compensation the import round-trip would
// accumulate an extraneous Rx(-90°) rotation. The spatial chain
//   p_lcc2 = Rz(180°) * Rx(90°) * Rz(180°) * p_ply
// simplifies to Rx(-90°) = (x, z, -y). Positions, rotation quaternions, and
// degree-1 SH coefficients all receive the same Rx(-90°) transform so each
// gaussian's orientation, shape, and first-order view-dependent lighting
// stay consistent.
//
//   Position:     (x, y, z) → (x, z, -y).
//   Quaternion:   q' = Rx(-90°) * q  (left-multiply, w-first order).
//   SH l=1:       (y→z, z→-y, x unchanged) per channel.
//
// Higher-degree SH (l≥2) are not compensated; their angular power is small
// enough that the visual impact is negligible for export. Returns the scene
// AABB in LCC2 space (splat-center extents, not scale-expanded).
const applyLcc2CoordinateTransform = (dataTable: DataTable, maxSHBands: number): { min: [number, number, number]; max: [number, number, number] } => {
    const N = dataTable.numRows;
    const xs = dataTable.getColumnByName('x')!.data as Float32Array;
    const ys = dataTable.getColumnByName('y')!.data as Float32Array;
    const zs = dataTable.getColumnByName('z')!.data as Float32Array;
    const r0 = dataTable.getColumnByName('rot_0')!.data as Float32Array;
    const r1 = dataTable.getColumnByName('rot_1')!.data as Float32Array;
    const r2 = dataTable.getColumnByName('rot_2')!.data as Float32Array;
    const r3 = dataTable.getColumnByName('rot_3')!.data as Float32Array;
    const SQRT1_2 = Math.SQRT1_2;

    // Degree-1 SH rotation. getColumnByName returns Column|null, so test for
    // null (not undefined) — an earlier version used `!== undefined` which is
    // always true for a Column|null return and would crash on SH-less scenes.
    const shCoeffs = [0, 3, 8, 15][maxSHBands];
    let shCols: Float32Array[] | null = null;
    if (shCoeffs >= 3 && dataTable.getColumnByName('f_rest_0')) {
        shCols = [];
        for (let ch = 0; ch < 3; ++ch) {
            const base = ch * shCoeffs;
            shCols.push(
                dataTable.getColumnByName(`f_rest_${base + 0}`)!.data as Float32Array,
                dataTable.getColumnByName(`f_rest_${base + 1}`)!.data as Float32Array
            );
        }
    }

    for (let i = 0; i < N; ++i) {
        const x = xs[i];
        const y = ys[i];
        const z = zs[i];
        xs[i] = x;
        ys[i] = z;
        zs[i] = -y;

        // q' = Rx(-90°) * q  (left-multiply, w-first order)
        const qw = r0[i], qx = r1[i], qy = r2[i], qz = r3[i];
        r0[i] = (qw + qx) * SQRT1_2;
        r1[i] = (qx - qw) * SQRT1_2;
        r2[i] = (qy + qz) * SQRT1_2;
        r3[i] = (qz - qy) * SQRT1_2;

        // SH l=1: rotate per-channel (y→z, z→-y, x unchanged)
        if (shCols) {
            for (let ch = 0; ch < 3; ++ch) {
                const s0 = shCols[ch * 2 + 0], s1 = shCols[ch * 2 + 1];
                const v0 = s0[i], v1 = s1[i];
                s0[i] = v1;
                s1[i] = -v0;
            }
        }
    }

    let minX = Infinity, minY = Infinity, minZ = Infinity;
    let maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity;
    for (let i = 0; i < N; ++i) {
        const x = xs[i], y = ys[i], z = zs[i];
        if (x < minX) minX = x;
        if (y < minY) minY = y;
        if (z < minZ) minZ = z;
        if (x > maxX) maxX = x;
        if (y > maxY) maxY = y;
        if (z > maxZ) maxZ = z;
    }
    return { min: [minX, minY, minZ], max: [maxX, maxY, maxZ] };
};

// LCC2 node metadata shape (matches the v0.0.3 schema).
type Lcc2NodeRef = { name: number; start: number; count: number };
type Lcc2Aabb = { min: [number, number, number]; max: [number, number, number] };

// Build a hybrid octree+binary spatial tree on the finest splats.
// The first 3 bits use OCTREE: the scene AABB is halved on ALL THREE axes
// simultaneously (octant 0..7). Bits 4..leafBits use round-robin BINARY
// subdivision within each octant.
//
//   leafBits: total bits in leaf path (>=3 for octree)
//   treeDepth = leafBits - 2  (1 octree level + binary levels)
//   totalLevels metadata = treeDepth
//
// This matches the reference LCC2 structure (雕像群): 8 root children, each
// with its own binary subtree, ~4-8 files per LOD level.
//
// Returns:
//   leafNode[i]   - leafBits-bit leaf code for finest splat i; top 3 bits = octant
//   leafCount[l]  - number of finest splats in leaf l (0 => empty leaf)
//   nodeAabbs[D]  - array (indexed 0..2^(D+2)-1) of tight AABBs per depth-D node
//   numLeaves     - 2^leafBits
const buildLcc2SpatialTree = (
    xs: Float32Array, ys: Float32Array, zs: Float32Array,
    N: number, leafBits: number, sceneAabb: Lcc2Aabb
): { leafNode: Uint32Array; leafCount: Uint32Array; nodeAabbs: Lcc2Aabb[][]; numLeaves: number } => {
    const numLeaves = 1 << leafBits;
    const leafNode = new Uint32Array(N);
    const leafCount = new Uint32Array(numLeaves);
    const [sMin0, sMin1, sMin2] = sceneAabb.min;
    const [sMax0, sMax1, sMax2] = sceneAabb.max;
    const treeDepth = leafBits - 2; // 1 octree + (leafBits-3) binary = leafBits-2

    // Descent: first 3 bits = octree (all 3 axes simultaneously), then round-
    // robin binary within the octant sub-region. O(N*leafBits).
    for (let i = 0; i < N; ++i) {
        let n0 = sMin0, n1 = sMin1, n2 = sMin2, x0 = sMax0, x1 = sMax1, x2 = sMax2;
        const px = xs[i], py = ys[i], pz = zs[i];

        // Octree: 3 bits encoding all axes simultaneously
        const midX = (n0 + x0) * 0.5;
        const midY = (n1 + x1) * 0.5;
        const midZ = (n2 + x2) * 0.5;
        const bX = px <= midX ? 0 : 1;
        const bY = py <= midY ? 0 : 1;
        const bZ = pz <= midZ ? 0 : 1;
        if (bX === 0) x0 = midX; else n0 = midX;
        if (bY === 0) x1 = midY; else n1 = midY;
        if (bZ === 0) x2 = midZ; else n2 = midZ;
        let code = (bX << 2) | (bY << 1) | bZ; // [2:0] = octant

        // Binary: remaining leafBits-3 bits, one axis per bit
        for (let d = 3; d < leafBits; ++d) {
            const axis = d % 3;
            let bit: number;
            if (axis === 0) {
                const mid = (n0 + x0) * 0.5;
                bit = px <= mid ? 0 : 1;
                if (bit === 0) x0 = mid; else n0 = mid;
            } else if (axis === 1) {
                const mid = (n1 + x1) * 0.5;
                bit = py <= mid ? 0 : 1;
                if (bit === 0) x1 = mid; else n1 = mid;
            } else {
                const mid = (n2 + x2) * 0.5;
                bit = pz <= mid ? 0 : 1;
                if (bit === 0) x2 = mid; else n2 = mid;
            }
            code = (code << 1) | bit;
        }
        leafNode[i] = code;
        leafCount[code]++;
    }

    // Leaf AABBs (tight, over NON-EMPTY leaves only).
    const leafMin = new Float32Array(numLeaves * 3);
    const leafMax = new Float32Array(numLeaves * 3);
    leafMin.fill(Infinity);
    leafMax.fill(-Infinity);
    for (let i = 0; i < N; ++i) {
        const o = leafNode[i] * 3;
        const x = xs[i], y = ys[i], z = zs[i];
        if (x < leafMin[o]) leafMin[o] = x;
        if (y < leafMin[o + 1]) leafMin[o + 1] = y;
        if (z < leafMin[o + 2]) leafMin[o + 2] = z;
        if (x > leafMax[o]) leafMax[o] = x;
        if (y > leafMax[o + 1]) leafMax[o + 1] = y;
        if (z > leafMax[o + 2]) leafMax[o + 2] = z;
    }

    // Per-depth node AABBs. Depth D has 2^(D+2) nodes for D>=1; each covers
    // 2^(leafBits-D-2) leaves. Union only non-empty leaves; dead nodes get
    // degenerate AABB (pruned on emit).
    const emptyMin0 = (sMin0 + sMax0) * 0.5, emptyMin1 = (sMin1 + sMax1) * 0.5, emptyMin2 = (sMin2 + sMax2) * 0.5;
    const nodeAabbs: Lcc2Aabb[][] = [null as never]; // index 0 unused
    for (let D = 1; D <= treeDepth; ++D) {
        const shift = leafBits - D - 2;
        const numNodes = 1 << (D + 2);
        const arr: Lcc2Aabb[] = new Array(numNodes);
        for (let n = 0; n < numNodes; ++n) {
            const start = n << shift;
            const end = start + (1 << shift);
            let mn0 = Infinity, mn1 = Infinity, mn2 = Infinity;
            let mx0 = -Infinity, mx1 = -Infinity, mx2 = -Infinity;
            for (let l = start; l < end; ++l) {
                if (leafCount[l] === 0) continue;
                const o = l * 3;
                if (leafMin[o] < mn0) mn0 = leafMin[o];
                if (leafMin[o + 1] < mn1) mn1 = leafMin[o + 1];
                if (leafMin[o + 2] < mn2) mn2 = leafMin[o + 2];
                if (leafMax[o] > mx0) mx0 = leafMax[o];
                if (leafMax[o + 1] > mx1) mx1 = leafMax[o + 1];
                if (leafMax[o + 2] > mx2) mx2 = leafMax[o + 2];
            }
            if (!isFinite(mn0)) {
                arr[n] = { min: [emptyMin0, emptyMin1, emptyMin2], max: [emptyMin0, emptyMin1, emptyMin2] };
            } else {
                arr[n] = { min: [mn0, mn1, mn2], max: [mx0, mx1, mx2] };
            }
        }
        nodeAabbs[D] = arr;
    }

    return { leafNode, leafCount, nodeAabbs, numLeaves };
};

// Build the nested LCC2 tree JSON for the root's children. Depth 1 uses octree
// (8 children, octant digit 0-7); depth >=2 uses binary (2 children, 0/1 bits).
// Build node ID from depth/nodeIdx. Matches buildLcc2TreeNode's convention.
//   depth 1: octant → `0_{octant}`  (octant 0..7)
//   depth 2: octant + 1 binary bit → `0_{octant}_{bit}`
//   depth 3+: octant + (depth-1) binary bits
const getNodeId = (depth: number, nodeIdx: number): string => {
    let id = '0';
    if (depth >= 1) {
        const octant = depth > 1 ? (nodeIdx >> (depth - 1)) : nodeIdx;
        id += `_${octant}`;
        for (let d = depth - 2; d >= 0; --d) {
            id += `_${(nodeIdx >> d) & 1}`;
        }
    }
    return id;
};

// Fully-empty subtrees are pruned; data.3dgs only emitted when count>0.
// Returns null for dead nodes (caller drops them).
const buildLcc2TreeNode = (
    depth: number, nodeIdx: number, treeDepth: number, leafBits: number,
    nodeAabbs: Lcc2Aabb[][], nodeRefs: Lcc2NodeRef[][], leafCount: Uint32Array
): any => {
    // Dead check: sum finest splats over this node's leaf range.
    const shift = leafBits - depth - 2;
    const leafStart = nodeIdx << shift;
    const leafEnd = leafStart + (1 << shift);
    let subtreeCount = 0;
    for (let l = leafStart; l < leafEnd; ++l) subtreeCount += leafCount[l];
    if (subtreeCount === 0) return null; // prune

    const id = getNodeId(depth, nodeIdx);
    const aabb = nodeAabbs[depth][nodeIdx];
    const ref = nodeRefs[depth][nodeIdx];
    const data = ref && ref.count > 0 ? { '3dgs': ref } : null;

    if (depth === treeDepth) {
        return { id, boundingBox: aabb, childNum: 0, data };
    }

    // All depths >=1 use binary splitting (2 children).
    // The 8-way octree split only occurs at depth 0→1, handled manually when
    // building the root's children.
    const branchFactor = 2;
    const childNodes: (any)[] = [];
    for (let m = 0; m < branchFactor; ++m) {
        const cIdx = nodeIdx * branchFactor + m;
        const c = buildLcc2TreeNode(depth + 1, cIdx, treeDepth, leafBits, nodeAabbs, nodeRefs, leafCount);
        if (c) childNodes.push(c);
    }
    const child: Record<string, any> = {};
    for (let i = 0; i < childNodes.length; ++i) {
        child[String(i)] = childNodes[i];
    }
    return { id, boundingBox: aabb, childNum: childNodes.length, data, child };
};

// LCC2 (Lixel CyberColor 2) directory-format serialization. Phase 1 writes a
// single LOD; Phase 2 (lodLevels>1) builds a multi-level LOD tree.
//
// Phase 2 LOD generation:
//   - A round-robin axis binary tree of depth L is built on the finest splats.
//   - LOD level k (0=finest..L-1=coarsest) is a 1/2^k interval sample of the
//     finest, binned by depth-(L-k) tree node. Each node's [start,count] is a
//     contiguous span in its level's chunk.
//   - The finest level (k=0) is written directly from the original DataTable
//     with `indices` = the node-ordered full permutation (no clone; writeSog
//     skips its internal Morton sort and emits in our order).
//   - Coarser levels (k≥1) are written from a `clone({ rows })` subset (sized
//     to N/2^k, never full-size) with identity `indices` to preserve node
//     order. Peak memory = finest + one smaller clone.
//   - splatFiles is ordered coarsest→finest (depth 1 → index 0), matching the
//     reference sample; node.data.3dgs.name = depth-1.
const serializeLcc2 = async (splats: Splat[], options: Lcc2ExportOptions, fs: FileSystem): Promise<void> => {
    const { name, serializeSettings, splatIdx } = options;
    const { iterations = 10, events } = serializeSettings;
    const splatType = options.splatType ?? '.sog';
    // Clamp lodLevels to [1,6]. Max 6 matches UE plugin compatibility.
    let lodLevels = Math.max(1, Math.min(6, options.lodLevels ?? 6));

    const selectedSplats = splatIdx?.length ? splatIdx.map(i => splats[i]) : splats;

    await fs.mkdir(`${name}/data/3dgs`);

    configureSplatTransform();
    splatTransformLogger.setRenderer(createProgressRenderer('Exporting LCC2', events));

    // Build the splat-transform DataTable ONCE (PLY space). SingleSplat.read
    // pre-applies the PLY-style 180° Z flip + world transform.
    const dataTable = extractDataTable(selectedSplats, serializeSettings);
    const N = dataTable.numRows;

    // Convert PLY-space data to LCC2-native space (in-place). Done before any
    // clone so coarser-level subsets inherit the transform.
    const maxSHBands = serializeSettings.maxSHBands ?? 3;
    const boundingBox = applyLcc2CoordinateTransform(dataTable, maxSHBands);

    const fileType = maxSHBands > 0 ? 'quality' : 'portable';
    const guid = crypto.randomUUID().replace(/-/g, '');

    // splatFiles[k-file-index] : depth D -> index D-1 (coarsest first).
    // chunkPaths[k] : level k (0=finest). splatFiles[d] = chunkPaths[L-1-d].
    const splatFiles: string[] = [];
    const lodSplats: number[] = [];
    let root: any;

    try {
        // Auto-select tree depth (LOD levels).
        //   - safeTreeDepth: minimum for chunk safety (per-depth total ≤ SOG_CHUNK_TARGET)
        //   - User slider value is honored; only raised when needed for chunk safety.
        //   - Per-depth merging means small nodes don't cause file explosion.
        const SOG_CHUNK_TARGET = 3_000_000;
        const safeTreeDepth = Math.max(1, Math.ceil(Math.log2(N / SOG_CHUNK_TARGET)) - 2);
        const treeDepth = Math.min(10, Math.max(safeTreeDepth, lodLevels));
        const leafBits = treeDepth + 2; // 3 octree + (treeDepth-1) binary
        if (treeDepth > lodLevels) {
            console.warn(
                `[LCC2] auto-raised lodLevels ${lodLevels}→${treeDepth} ` +
                `(N=${N.toLocaleString()}, SOG_CHUNK_TARGET=${SOG_CHUNK_TARGET.toLocaleString()})`
            );
        }
        // Rough encode-time estimate.
        const shFactor = maxSHBands > 0 ? 1 : 0.25;
        const estMin = Math.max(1, Math.round((N / 3.8e6) * 10 * shFactor));
        console.warn(`[LCC2] N=${N.toLocaleString()} treeDepth=${treeDepth} SH=${maxSHBands} est ~${estMin} min`);
        lodLevels = treeDepth;

        if (treeDepth <= 1) {
            // ---- Phase 1: single LOD ----
            const lodFileName = `${name}_LOD0_0.sog`;
            const chunkPath = `${name}/data/3dgs/${lodFileName}`;
            await writeSogInternal({
                filename: chunkPath,
                dataTable,
                bundle: true,
                iterations,
                createDevice: createGpuDevice
            }, fs);
            splatFiles.push(`data/3dgs/${lodFileName}`);
            lodSplats.push(N);
            root = {
                id: '0',
                boundingBox,
                childNum: 1,
                data: null,
                splatFiles,
                meshFiles: [] as string[],
                bvhFiles: [] as string[],
                child: {
                    '0': {
                        id: '0_0',
                        boundingBox,
                        childNum: 0,
                        data: { '3dgs': { name: 0, start: 0, count: N } }
                    }
                }
            };
        } else {
            // ---- Phase 2: multi-level LOD with per-depth chunking ----
            //
            // Each depth D (1..treeDepth) holds one LOD level. All nodes at
            // depth D are concatenated into one contiguous DataTable, which is
            // written as 1..N .sog files (chunks <= SOG_CHUNK_TARGET splats).
            // Each node gets {name, start, count} into the level's files.
            // This matches the reference structure: 雕像群 = ~6 files/level.
            const xs = dataTable.getColumnByName('x')!.data as Float32Array;
            const ys = dataTable.getColumnByName('y')!.data as Float32Array;
            const zs = dataTable.getColumnByName('z')!.data as Float32Array;

            console.warn(`[LCC2] building octree: N=${N.toLocaleString()}, leafBits=${leafBits} treeDepth=${treeDepth}`);
            const { leafNode, leafCount, nodeAabbs } = buildLcc2SpatialTree(xs, ys, zs, N, leafBits, boundingBox);
            console.warn(`[LCC2] octree done, ${1 << leafBits} leaves`);

            // nodeRefs[D][n] = {name, start, count}. name=index into splatFiles.
            const nodeRefs: Lcc2NodeRef[][] = [null as never];
            const lodSplatsByLevel = new Array(treeDepth).fill(0);
            // Track chunk index per LOD level; k=0=finest.
            const chunkIdxByLevel = new Array(treeDepth).fill(0);
            const srcCols = dataTable.columns;
            const numCols = srcCols.length;

            // Encode coarsest (depth 1) → finest (depth treeDepth).
            for (let D = 1; D <= treeDepth; ++D) {
                const k = treeDepth - D;     // LOD level index (0=finest)
                const step = Math.max(1, Math.round(1 + k * 0.5)); // LOD0=1(100%)→LOD5=4(25%)
                const shift = leafBits - D - 2;
                const numNodes = 1 << (D + 2); // depth 1=8, depth 2=16, ...
                const refs: Lcc2NodeRef[] = new Array(numNodes);

                // ---- Pass 1: count samples per node ----
                const counts = new Uint32Array(numNodes);
                for (let i = 0; i < N; i += step) {
                    counts[leafNode[i] >> shift]++;
                }

                // Force at least one sample for nodes that have splats but were
                // missed by interval sampling (sparse regions at coarser LODs).
                // Without this, nodes get data:null bounding boxes which crash
                // the UE plugin's LCC2Tree::ComputeError with a null-pointer
                // access at offset 0x128.
                for (let n = 0; n < numNodes; ++n) {
                    if (counts[n] > 0) continue;
                    const ls = n << shift;
                    const le = ls + (1 << shift);
                    let sc = 0;
                    for (let l = ls; l < le; ++l) sc += leafCount[l];
                    if (sc === 0) continue;
                    for (let i = 0; i < N; ++i) {
                        if ((leafNode[i] >> shift) === n) {
                            counts[n] = 1;
                            break;
                        }
                    }
                }

                // ---- Pass 2: collect per-node indices and build per-depth total ----
                // nodeIndices[n]: sorted finest indices belonging to this node
                const nodeIndicesArr: Uint32Array[] = new Array(numNodes);
                // nodeOffsets[n]: start position of node n in the depth-level concatenation
                const nodeOffsets: number[] = new Array(numNodes + 1);
                let levelTotal = 0;
                for (let n = 0; n < numNodes; ++n) {
                    nodeOffsets[n] = levelTotal;
                    const cnt = counts[n];
                    if (cnt === 0) continue;
                    const indices = new Uint32Array(cnt);
                    let w = 0;
                    for (let i = 0; i < N; i += step) {
                        if ((leafNode[i] >> shift) === n) indices[w++] = i;
                    }
                    // Fallback full scan for forced nodes (missed by interval sampling)
                    if (w < cnt) {
                        for (let i = 0; i < N && w < cnt; ++i) {
                            if ((leafNode[i] >> shift) === n) indices[w++] = i;
                        }
                    }
                    nodeIndicesArr[n] = indices;
                    levelTotal += cnt;
                }
                nodeOffsets[numNodes] = levelTotal;
                console.warn(`[LCC2] LOD${k}/depth${D}: ${numNodes - counts.filter(c => c === 0).length}/${numNodes} non-empty nodes, ${levelTotal.toLocaleString()} splats`);

                if (levelTotal === 0) {
                    for (let n = 0; n < numNodes; ++n) refs[n] = { name: -1, start: 0, count: 0 };
                    nodeRefs[D] = refs;
                    continue;
                }

                // ---- Pass 3: write files in chunks <= SOG_CHUNK_TARGET ----
                let fileStartNode = 0;
                let fileSplatOffset = 0;
                while (fileStartNode < numNodes) {
                    // Find end node for this chunk.
                    let chunkSplatCount = 0;
                    let endNode = fileStartNode;
                    while (endNode < numNodes) {
                        const nxt = chunkSplatCount + counts[endNode];
                        if (nxt > 0 && nxt > SOG_CHUNK_TARGET) break; // don't split a node mid-way
                        chunkSplatCount = nxt;
                        endNode++;
                    }
                    if (chunkSplatCount === 0) break;

                    // Build chunk DataTable: concatenate indices of nodes [fileStartNode..endNode-1].
                    const chunkIndices = new Uint32Array(chunkSplatCount);
                    let wi = 0;
                    for (let n = fileStartNode; n < endNode; ++n) {
                        if (counts[n] > 0) {
                            chunkIndices.set(nodeIndicesArr[n], wi);
                            wi += counts[n];
                        }
                    }

                    // Column-by-column from source for memory safety.
                    const chunkCols: Column[] = new Array(numCols);
                    for (let ci = 0; ci < numCols; ++ci) {
                        const src = srcCols[ci].data as Float32Array;
                        const dst = new Float32Array(chunkSplatCount);
                        for (let i = 0; i < chunkSplatCount; ++i) dst[i] = src[chunkIndices[i]];
                        chunkCols[ci] = new Column(srcCols[ci].name, dst);
                    }
                    const chunkTable = new DataTable(chunkCols, dataTable.transform);

                    const chunkIdx = chunkIdxByLevel[k]++;
                    const lodFileName = `${name}_LOD${k}_${chunkIdx}.sog`;
                    const chunkPath = `${name}/data/3dgs/${lodFileName}`;
                    events?.fire('progressUpdate', {
                        text: `depth ${D}/${treeDepth}: ${chunkSplatCount.toLocaleString()} splats`,
                        progress: 100 * D / treeDepth
                    });
                    console.warn(`[LCC2] LOD${k}/chunk${chunkIdx}: nodes[${fileStartNode}..${endNode - 1}] ${chunkSplatCount.toLocaleString()} splats → ${chunkPath}`);

                    const identity = new Uint32Array(chunkSplatCount);
                    for (let i = 0; i < chunkSplatCount; ++i) identity[i] = i;
                    await writeSogInternal({
                        filename: chunkPath,
                        dataTable: chunkTable,
                        bundle: true,
                        iterations,
                        createDevice: createGpuDevice,
                        indices: identity
                    }, fs);

                    const fileIdx = splatFiles.length;
                    splatFiles.push(`data/3dgs/${lodFileName}`);
                    console.warn(`[LCC2] LOD${k}/chunk${chunkIdx}: done`);

                    // Assign refs for nodes in this chunk.
                    let nodeOffset = 0;
                    for (let n = fileStartNode; n < endNode; ++n) {
                        const cnt = counts[n];
                        if (cnt > 0) {
                            refs[n] = { name: fileIdx, start: nodeOffset, count: cnt };
                            lodSplatsByLevel[k] += cnt;
                        } else {
                            refs[n] = { name: -1, start: 0, count: 0 };
                        }
                        nodeOffset += cnt;
                    }

                    fileStartNode = endNode;
                    fileSplatOffset += chunkSplatCount;
                    (globalThis as { gc?: () => void }).gc?.();
                }

                nodeRefs[D] = refs;
            }

            // Coarsest-first order matching reference convention.
            for (let k = treeDepth - 1; k >= 0; --k) lodSplats.push(lodSplatsByLevel[k]);

            // Assemble the nested tree. Root children = 8 octants at depth 1.
            const child: Record<string, any> = {};
            let childNum = 0;
            for (let oct = 0; oct < 8; ++oct) {
                const c = buildLcc2TreeNode(1, oct, treeDepth, leafBits, nodeAabbs, nodeRefs, leafCount);
                if (c) {
                    child[String(childNum++)] = c;
                }
            }
            root = {
                id: '0',
                boundingBox,
                childNum,
                data: null,
                splatFiles,
                meshFiles: [] as string[],
                bvhFiles: [] as string[],
                child
            };
        }
    } catch (err) {
        splatTransformLogger.unwindAll(true);
        throw err;
    }

    const totalSplats = lodSplats.reduce((a, b) => a + b, 0);

    const meta = {
        version: '0.0.3',
        name: name || 'ReSplat Lcc2 Splats',
        description: 'ReSplat exported LCC2 splats',
        guid,
        source: 'resplat',
        dataType: 'Editor',
        epsg: 0,
        offset: [0, 0, 0],
        shift: [0, 0, 0],
        scale: [1, 1, 1],
        fileType,
        totalSplats,
        lodSplats,
        totalLevels: lodLevels,
        splatType,
        virtualLoD: null as null,
        env: null as null,
        splatExtraAttributes: null as null,
        renderingHints: {
            renderMethod: 'splatting',
            renderMethodVariant: 'ewa',
            sortingMethod: 'depth',
            cameraModel: 'pinhole',
            colorSpace: 'srgb_rec709_display'
        },
        root
    };

    // Write the metadata file
    const jsonWriter = await fs.createWriter(`${name}/${name}.lcc2`);
    await jsonWriter.write(new TextEncoder().encode(JSON.stringify(meta, null, 2)));
    await jsonWriter.close();

    // ZIP fallback: if writing into a MemoryFileSystem (browser without
    // showDirectoryPicker), package the in-memory tree into a ZIP download.
    if (fs instanceof MemoryFileSystem) {
        const downloadFs = new BrowserFileSystem(`${name}.zip`);
        const zipWriter = await downloadFs.createWriter(`${name}.zip`);
        const zipFs = new ZipFileSystem(zipWriter);
        try {
            for (const [filename, data] of fs.results.entries()) {
                const writer = await zipFs.createWriter(filename);
                await writer.write(data);
                await writer.close();
            }
        } finally {
            await zipFs.close();
        }
    }
};

export {
    Writer,
    serializePly,
    serializePlyToWriter,
    serializePlyCompressed,
    serializeStandardPly,
    serializeSplat,
    serializeSog,
    serializeLcc2,
    serializeViewer,
    AnimTrack,
    CameraPose,
    Camera,
    Annotation,
    PostEffectSettings,
    defaultPostEffectSettings,
    ExperienceSettings,
    SerializeSettings,
    SogSettings,
    Lcc2ExportOptions,
    ViewerExportSettings,
    SingleSplat,
    SplatTransformCache
};
